//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dll_MA_IFacturacion.xsasvrFileReceiverService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SOAPException", Namespace="http://soap.xml.javax")]
    [System.SerializableAttribute()]
    public partial class SOAPException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dll_MA_IFacturacion.xsasvrFileReceiverService.Throwable causeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dll_MA_IFacturacion.xsasvrFileReceiverService.Throwable cause {
            get {
                return this.causeField;
            }
            set {
                if ((object.ReferenceEquals(this.causeField, value) != true)) {
                    this.causeField = value;
                    this.RaisePropertyChanged("cause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Throwable", Namespace="http://lang.java")]
    [System.SerializableAttribute()]
    public partial class Throwable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xsafilereceiver.webservices.manager.xsa.tralix.com", ConfigurationName="xsasvrFileReceiverService.FileReceiverServicePortType")]
    public interface FileReceiverServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dll_MA_IFacturacion.xsasvrFileReceiverService.SOAPException), Action="", Name="SOAPException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string obtenerEstadoDocumento(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dll_MA_IFacturacion.xsasvrFileReceiverService.SOAPException), Action="", Name="SOAPException")]
        void guardarDocumento(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Dll_MA_IFacturacion.xsasvrFileReceiverService.SOAPException), Action="", Name="SOAPException")]
        void guardarDocumentoB2B(string in0, string in1, string in2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileReceiverServicePortTypeChannel : Dll_MA_IFacturacion.xsasvrFileReceiverService.FileReceiverServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileReceiverServicePortTypeClient : System.ServiceModel.ClientBase<Dll_MA_IFacturacion.xsasvrFileReceiverService.FileReceiverServicePortType>, Dll_MA_IFacturacion.xsasvrFileReceiverService.FileReceiverServicePortType {
        
        public FileReceiverServicePortTypeClient() {
        }
        
        public FileReceiverServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileReceiverServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReceiverServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReceiverServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string obtenerEstadoDocumento(string in0, string in1, string in2) {
            return base.Channel.obtenerEstadoDocumento(in0, in1, in2);
        }
        
        public void guardarDocumento(string in0, string in1, string in2, string in3, string in4) {
            base.Channel.guardarDocumento(in0, in1, in2, in3, in4);
        }
        
        public void guardarDocumentoB2B(string in0, string in1, string in2) {
            base.Channel.guardarDocumentoB2B(in0, in1, in2);
        }
    }
}
