------------------------------------------------------------------------------------------------------------------------------------------------ 
If Exists ( Select * From Sysobjects (NoLock) Where Name = 'BI_UNI_RPT__DTS__ClavesSSA' and xType = 'U' ) 
   Drop Table BI_UNI_RPT__DTS__ClavesSSA 
Go--#SQL 

Create Table BI_UNI_RPT__DTS__ClavesSSA  
(
	Consecutivo int Not Null Default 0, 
	ClaveSSA varchar(20) Not Null Default '', 
	DescripcionSSA varchar(max) Not Null Default '', 
	Presentacion varchar(500) Not Null Default '', 
	CantidadMinima int Not Null Default 0, 
	CantidadMaxima int Not Null Default 0		
)
Go--#SQL    


/* 
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 1, '010.000.0101.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 2, '010.000.0103.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 3, '010.000.0104.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 4, '010.000.0108.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 5, '010.000.0109.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 6, '010.000.0204.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 7, '010.000.0247.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 8, '010.000.0254.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 9, '010.000.0261.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 10, '010.000.0262.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 11, '010.000.0265.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 12, '010.000.0291.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 13, '010.000.0402.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 14, '010.000.0426.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 15, '010.000.0437.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 16, '010.000.0472.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 17, '010.000.0473.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 18, '010.000.0474.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 19, '010.000.0476.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 20, '010.000.0502.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 21, '010.000.0504.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 22, '010.000.0524.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 23, '010.000.0525.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 24, '010.000.0530.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 25, '010.000.0539.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 26, '010.000.0561.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 27, '010.000.0566.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 28, '010.000.0570.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 29, '010.000.0572.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 30, '010.000.0573.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 31, '010.000.0574.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 32, '010.000.0592.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 33, '010.000.0593.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 34, '010.000.0596.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 35, '010.000.0597.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 36, '010.000.0599.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 37, '010.000.0611.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 38, '010.000.0612.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 39, '010.000.0614.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 40, '010.000.0615.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 41, '010.000.0621.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 42, '010.000.0622.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 43, '010.000.0623.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 44, '010.000.0624.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 45, '010.000.0624.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 46, '010.000.0655.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 47, '010.000.0657.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 48, '010.000.0871.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 49, '010.000.1006.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 50, '010.000.1007.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 51, '010.000.1022.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 52, '010.000.1042.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 53, '010.000.1093.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 54, '010.000.1095.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 55, '010.000.1096.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 56, '010.000.1206.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 57, '010.000.1207.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 58, '010.000.1223.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 59, '010.000.1233.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 60, '010.000.1234.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 61, '010.000.1234.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 62, '010.000.1241.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 63, '010.000.1242.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 64, '010.000.1272.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 65, '010.000.1308.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 66, '010.000.1308.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 67, '010.000.1309.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 68, '010.000.1542.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 69, '010.000.1546.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 70, '010.000.1551.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 71, '010.000.1552.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 72, '010.000.1700.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 73, '010.000.1701.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 74, '010.000.1703.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 75, '010.000.1705.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 76, '010.000.1706.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 77, '010.000.1708.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 78, '010.000.1711.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 79, '010.000.1732.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 80, '010.000.1759.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 81, '010.000.1903.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 82, '010.000.1911.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 83, '010.000.1926.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 84, '010.000.1929.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 85, '010.000.1939.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 86, '010.000.1940.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 87, '010.000.1941.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 88, '010.000.1969.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 89, '010.000.1971.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 90, '010.000.1981.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 91, '010.000.1991.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 92, '010.000.2016.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 93, '010.000.2018.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 94, '010.000.2040.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 95, '010.000.2111.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 96, '010.000.2116.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 97, '010.000.2126.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 98, '010.000.2128.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 99, '010.000.2128.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 100, '010.000.2132.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 101, '010.000.2133.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 102, '010.000.2136.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 103, '010.000.2138.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 104, '010.000.2142.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 105, '010.000.2144.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 106, '010.000.2147.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 107, '010.000.2154.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 108, '010.000.2155.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 109, '010.000.2156.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 110, '010.000.2188.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 111, '010.000.2191.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 112, '010.000.2195.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 113, '010.000.2230.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 114, '010.000.2230.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 115, '010.000.2247.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 116, '010.000.2248.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 117, '010.000.2262.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 118, '010.000.2263.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 119, '010.000.2301.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 120, '010.000.2302.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 121, '010.000.2304.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 122, '010.000.2304.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 123, '010.000.2307.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 124, '010.000.2308.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 125, '010.000.2331.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 126, '010.000.2462.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 127, '010.000.2501.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 128, '010.000.2504.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 129, '010.000.2520.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 130, '010.000.2540.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 131, '010.000.2542.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 132, '010.000.2610.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 133, '010.000.2617.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 134, '010.000.2622.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 135, '010.000.2626.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 136, '010.000.2630.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 137, '010.000.2707.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 138, '010.000.2714.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 139, '010.000.2736.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 140, '010.000.3044.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 141, '010.000.3111.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 142, '010.000.3112.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 143, '010.000.3307.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 144, '010.000.3308.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 145, '010.000.3309.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 146, '010.000.3407.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 147, '010.000.3409.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 148, '010.000.3413.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 149, '010.000.3417.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 150, '010.000.3422.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 151, '010.000.3432.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 152, '010.000.3451.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 153, '010.000.3461.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 154, '010.000.3617.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 155, '010.000.3619.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 156, '010.000.3620.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 157, '010.000.3629.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 158, '010.000.3671.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 159, '010.000.3674.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 160, '010.000.4028.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 161, '010.000.4095.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 162, '010.000.4096.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 163, '010.000.4107.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 164, '010.000.4110.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 165, '010.000.4111.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 166, '010.000.4117.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 167, '010.000.4122.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 168, '010.000.4148.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 169, '010.000.4161.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 170, '010.000.4163.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 171, '010.000.4164.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 172, '010.000.4176.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 173, '010.000.4184.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 174, '010.000.4185.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 175, '010.000.4191.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 176, '010.000.4201.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 177, '010.000.4222.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 178, '010.000.4223.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 179, '010.000.4224.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 180, '010.000.4242.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 181, '010.000.4246.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 182, '010.000.4246.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 183, '010.000.4255.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 184, '010.000.4261.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 185, '010.000.4263.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 186, '010.000.4264.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 187, '010.000.4290.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 188, '010.000.4299.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 189, '010.000.4300.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 190, '010.000.4302.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 191, '010.000.4326.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 192, '010.000.4329.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 193, '010.000.4330.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 194, '010.000.4332.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 195, '010.000.4356.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 196, '010.000.4358.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 197, '010.000.4359.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 198, '010.000.4372.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 199, '010.000.4376.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 200, '010.000.4439.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 201, '010.000.4504.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 202, '010.000.4514.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 203, '010.000.4515.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 204, '010.000.4582.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 205, '010.000.5079.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 206, '010.000.5099.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 207, '010.000.5105.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 208, '010.000.5106.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 209, '010.000.5107.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 210, '010.000.5165.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 211, '010.000.5169.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 212, '010.000.5176.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 213, '010.000.5186.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 214, '010.000.5186.02', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 215, '010.000.5229.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 216, '010.000.5255.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 217, '010.000.5267.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 218, '010.000.5306.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 219, '010.000.5309.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 220, '010.000.5309.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 221, '010.000.5309.02', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 222, '010.000.5319.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 223, '010.000.5330.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 224, '010.000.5332.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 225, '010.000.5333.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 226, '010.000.5358.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 227, '010.000.5359.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 228, '010.000.5363.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 229, '010.000.5365.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 230, '010.000.5381.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 231, '010.000.5386.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 232, '010.000.5395.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 233, '010.000.5418.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 234, '010.000.5436.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 235, '010.000.5451.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 236, '010.000.5461.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 237, '010.000.5463.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 238, '010.000.5469.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 239, '010.000.5501.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 240, '010.000.5505.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 241, '010.000.5541.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 242, '010.000.5551.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 243, '010.000.5551.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 244, '010.000.5552.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 245, '010.000.5552.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 246, '010.000.5621.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 247, '010.000.5660.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 248, '010.000.5661.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 249, '010.000.5662.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 250, '010.000.5935.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 251, '040.000.1544.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 252, '040.000.2096.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 253, '040.000.2097.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 254, '040.000.2098.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 255, '040.000.2100.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 256, '040.000.2103.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 257, '040.000.2106.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 258, '040.000.2108.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 259, '040.000.2164.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 260, '040.000.2499.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 261, '040.000.2500.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 262, '040.000.3204.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 263, '040.000.4027.00', '', '', 0, 0 )   

*/

Go--#SQL 

	Update C set ClaveSSA = replace(ClaveSSA, 'U', '') 
	From BI_UNI_RPT__DTS__ClavesSSA C 


Go--#SQL 

