If Not Exists ( Select * From Net_Arboles Where Arbol = 'CFGC' )  Insert Into Net_Arboles Values ( 'CFGC', 'Configuración Sitio Cliente', 'A', 1 )    Else Update Net_Arboles Set Nombre = 'Configuración Sitio Cliente', Status = 'A', Actualizado = 1 Where Arbol = 'CFGC'
If Not Exists ( Select * From Net_Arboles Where Arbol = 'CFGE' )  Insert Into Net_Arboles Values ( 'CFGE', 'Configuración Sitio Cliente Regional', 'A', 1 )    Else Update Net_Arboles Set Nombre = 'Configuración Sitio Cliente Regional', Status = 'A', Actualizado = 1 Where Arbol = 'CFGE'
If Not Exists ( Select * From Net_Arboles Where Arbol = 'CFGN' )  Insert Into Net_Arboles Values ( 'CFGN', 'Configuración general', 'A', 1 )    Else Update Net_Arboles Set Nombre = 'Configuración general', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN'
If Not Exists ( Select * From Net_Arboles Where Arbol = 'CFGR' )  Insert Into Net_Arboles Values ( 'CFGR', 'Configuración Sitio Central Regional', 'A', 1 )    Else Update Net_Arboles Set Nombre = 'Configuración Sitio Central Regional', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR'
If Not Exists ( Select * From Net_Arboles Where Arbol = 'CFGS' )  Insert Into Net_Arboles Values ( 'CFGS', 'Configuración Sitio Central', 'A', 1 )    Else Update Net_Arboles Set Nombre = 'Configuración Sitio Central', Status = 'A', Actualizado = 1 Where Arbol = 'CFGS'
Go--#SQL 

If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGC' and Rama = 1 )  Insert Into Net_Navegacion Values ( 'CFGC', 1, 'Configuración Sitio Cliente', -1, '', '', 0, '1', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configuración Sitio Cliente', Padre = -1, FormaLoad = '', GrupoOpciones = '', IdOrden = 0, RutaCompleta = '1', Status = 'A', Actualizado = 1 Where Arbol = 'CFGC' and Rama = 1
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGC' and Rama = 2 )  Insert Into Net_Navegacion Values ( 'CFGC', 2, 'Configurar conexión con Sitio Central', 1, 'FrmConfigurarConexionOficinaCentral', 'DllTransferenciaSoft', 5, '1|2', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar conexión con Sitio Central', Padre = 1, FormaLoad = 'FrmConfigurarConexionOficinaCentral', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 5, RutaCompleta = '1|2', Status = 'A', Actualizado = 1 Where Arbol = 'CFGC' and Rama = 2
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGC' and Rama = 3 )  Insert Into Net_Navegacion Values ( 'CFGC', 3, 'Configurar integración', 1, 'FrmConfigIntegrarInformacion', 'DllTransferenciaSoft', 1, '1|3', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar integración', Padre = 1, FormaLoad = 'FrmConfigIntegrarInformacion', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 1, RutaCompleta = '1|3', Status = 'A', Actualizado = 1 Where Arbol = 'CFGC' and Rama = 3
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGC' and Rama = 4 )  Insert Into Net_Navegacion Values ( 'CFGC', 4, 'Configurar obtención de información', 1, 'FrmConfigObtenerInformacion', 'DllTransferenciaSoft', 3, '1|4', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar obtención de información', Padre = 1, FormaLoad = 'FrmConfigObtenerInformacion', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 3, RutaCompleta = '1|4', Status = 'A', Actualizado = 1 Where Arbol = 'CFGC' and Rama = 4
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGC' and Rama = 5 )  Insert Into Net_Navegacion Values ( 'CFGC', 5, 'Configurar respaldo de base de datos', 1, 'FrmConfigRespaldosBD', 'DllTransferenciaSoft', 7, '1|5', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar respaldo de base de datos', Padre = 1, FormaLoad = 'FrmConfigRespaldosBD', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 7, RutaCompleta = '1|5', Status = 'A', Actualizado = 1 Where Arbol = 'CFGC' and Rama = 5
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGE' and Rama = 1 )  Insert Into Net_Navegacion Values ( 'CFGE', 1, 'Configuración Sitio Cliente Regional', -1, '', '', 0, '1', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configuración Sitio Cliente Regional', Padre = -1, FormaLoad = '', GrupoOpciones = '', IdOrden = 0, RutaCompleta = '1', Status = 'A', Actualizado = 1 Where Arbol = 'CFGE' and Rama = 1
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGE' and Rama = 3 )  Insert Into Net_Navegacion Values ( 'CFGE', 3, 'Configurar obtención de información', 1, 'FrmConfigObtenerInformacion', 'DllTransferenciaSoft', 3, '1|3', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar obtención de información', Padre = 1, FormaLoad = 'FrmConfigObtenerInformacion', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 3, RutaCompleta = '1|3', Status = 'A', Actualizado = 1 Where Arbol = 'CFGE' and Rama = 3
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGE' and Rama = 4 )  Insert Into Net_Navegacion Values ( 'CFGE', 4, 'Configurar integración', 1, 'FrmConfigIntegrarInformacion', 'DllTransferenciaSoft', 3, '1|4', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar integración', Padre = 1, FormaLoad = 'FrmConfigIntegrarInformacion', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 3, RutaCompleta = '1|4', Status = 'A', Actualizado = 1 Where Arbol = 'CFGE' and Rama = 4
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 1 )  Insert Into Net_Navegacion Values ( 'CFGN', 1, 'Configuración', -1, '', '', 0, '1', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configuración', Padre = -1, FormaLoad = '', GrupoOpciones = '', IdOrden = 0, RutaCompleta = '1', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 1
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 3 )  Insert Into Net_Navegacion Values ( 'CFGN', 3, 'Grupos de usuarios', 15, 'FrmGruposUsuarios', 'DllFarmaciaSoft', 2, '1|15|3', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Grupos de usuarios', Padre = 15, FormaLoad = 'FrmGruposUsuarios', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 2, RutaCompleta = '1|15|3', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 3
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 4 )  Insert Into Net_Navegacion Values ( 'CFGN', 4, 'Permisos por grupo', 15, 'FrmGruposPermisos', 'DllFarmaciaSoft', 3, '1|15|4', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Permisos por grupo', Padre = 15, FormaLoad = 'FrmGruposPermisos', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 3, RutaCompleta = '1|15|4', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 4
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 5 )  Insert Into Net_Navegacion Values ( 'CFGN', 5, 'Estructura menú de opciones', 15, 'FrmEstructuraNavegacion', 'SC_SolutionsSystem', 4, '1|15|5', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Estructura menú de opciones', Padre = 15, FormaLoad = 'FrmEstructuraNavegacion', GrupoOpciones = 'SC_SolutionsSystem', IdOrden = 4, RutaCompleta = '1|15|5', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 5
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 6 )  Insert Into Net_Navegacion Values ( 'CFGN', 6, 'Catálogos', 1, '', '', 1, '1|6', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Catálogos', Padre = 1, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|6', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 6
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 7 )  Insert Into Net_Navegacion Values ( 'CFGN', 7, 'Personal', 43, 'FrmPersonal', 'DllFarmaciaSoft', 5, '1|6|43|7', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Personal', Padre = 43, FormaLoad = 'FrmPersonal', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 5, RutaCompleta = '1|6|43|7', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 7
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 8 )  Insert Into Net_Navegacion Values ( 'CFGN', 8, 'Geograficos', 6, '', '', 1, '1|6|8', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Geograficos', Padre = 6, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|6|8', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 8
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 9 )  Insert Into Net_Navegacion Values ( 'CFGN', 9, 'Estados', 8, 'FrmEstados', 'OficinaCentral', 3, '1|6|8|9', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Estados', Padre = 8, FormaLoad = 'FrmEstados', GrupoOpciones = 'OficinaCentral', IdOrden = 3, RutaCompleta = '1|6|8|9', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 9
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 10 )  Insert Into Net_Navegacion Values ( 'CFGN', 10, 'Municipios', 8, 'FrmMunicipios', 'OficinaCentral', 5, '1|6|8|10', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Municipios', Padre = 8, FormaLoad = 'FrmMunicipios', GrupoOpciones = 'OficinaCentral', IdOrden = 5, RutaCompleta = '1|6|8|10', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 10
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 11 )  Insert Into Net_Navegacion Values ( 'CFGN', 11, 'Colonias', 8, 'FrmColonias', 'OficinaCentral', 7, '1|6|8|11', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Colonias', Padre = 8, FormaLoad = 'FrmColonias', GrupoOpciones = 'OficinaCentral', IdOrden = 7, RutaCompleta = '1|6|8|11', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 11
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 12 )  Insert Into Net_Navegacion Values ( 'CFGN', 12, 'Jurisdicciones', 43, 'FrmJurisdicciones', 'OficinaCentral', 9, '1|6|43|12', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Jurisdicciones', Padre = 43, FormaLoad = 'FrmJurisdicciones', GrupoOpciones = 'OficinaCentral', IdOrden = 9, RutaCompleta = '1|6|43|12', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 12
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 14 )  Insert Into Net_Navegacion Values ( 'CFGN', 14, 'Farmacias', 43, 'FrmFarmacias', 'OficinaCentral', 3, '1|6|43|14', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Farmacias', Padre = 43, FormaLoad = 'FrmFarmacias', GrupoOpciones = 'OficinaCentral', IdOrden = 3, RutaCompleta = '1|6|43|14', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 14
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 15 )  Insert Into Net_Navegacion Values ( 'CFGN', 15, 'Administracion', 1, '', '', 3, '1|15', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Administracion', Padre = 1, FormaLoad = '', GrupoOpciones = '', IdOrden = 3, RutaCompleta = '1|15', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 15
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 16 )  Insert Into Net_Navegacion Values ( 'CFGN', 16, 'Regiones', 43, 'FrmRegiones', 'OficinaCentral', 5, '1|6|43|16', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Regiones', Padre = 43, FormaLoad = 'FrmRegiones', GrupoOpciones = 'OficinaCentral', IdOrden = 5, RutaCompleta = '1|6|43|16', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 16
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 17 )  Insert Into Net_Navegacion Values ( 'CFGN', 17, 'Sub-Regiones', 43, 'FrmSubRegiones', 'OficinaCentral', 7, '1|6|43|17', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Sub-Regiones', Padre = 43, FormaLoad = 'FrmSubRegiones', GrupoOpciones = 'OficinaCentral', IdOrden = 7, RutaCompleta = '1|6|43|17', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 17
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 18 )  Insert Into Net_Navegacion Values ( 'CFGN', 18, 'Configuración', 1, '', '', 5, '1|18', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configuración', Padre = 1, FormaLoad = '', GrupoOpciones = '', IdOrden = 5, RutaCompleta = '1|18', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 18
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 19 )  Insert Into Net_Navegacion Values ( 'CFGN', 19, 'Parametros Punto de Venta', 18, 'FrmParametrosPtoCliente', 'Configuracion', 9, '1|18|19', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Parametros Punto de Venta', Padre = 18, FormaLoad = 'FrmParametrosPtoCliente', GrupoOpciones = 'Configuracion', IdOrden = 9, RutaCompleta = '1|18|19', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 19
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 20 )  Insert Into Net_Navegacion Values ( 'CFGN', 20, 'Parametros Oficina Central', 18, 'FrmParametrosOC', 'Configuracion', 11, '1|18|20', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Parametros Oficina Central', Padre = 18, FormaLoad = 'FrmParametrosOC', GrupoOpciones = 'Configuracion', IdOrden = 11, RutaCompleta = '1|18|20', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 20
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 21 )  Insert Into Net_Navegacion Values ( 'CFGN', 21, 'Empresas', 43, 'FrmEmpresas', 'OficinaCentral', 1, '1|6|43|21', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Empresas', Padre = 43, FormaLoad = 'FrmEmpresas', GrupoOpciones = 'OficinaCentral', IdOrden = 1, RutaCompleta = '1|6|43|21', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 21
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 22 )  Insert Into Net_Navegacion Values ( 'CFGN', 22, 'Relación de Farmacias por Empresa', 18, 'FrmEmpresasFarmacias', 'OficinaCentral', 7, '1|18|22', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Relación de Farmacias por Empresa', Padre = 18, FormaLoad = 'FrmEmpresasFarmacias', GrupoOpciones = 'OficinaCentral', IdOrden = 7, RutaCompleta = '1|18|22', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 22
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 23 )  Insert Into Net_Navegacion Values ( 'CFGN', 23, 'Relación de Empresas-Estados', 18, 'FrmEmpresaEstado', 'OficinaCentral', 5, '1|18|23', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Relación de Empresas-Estados', Padre = 18, FormaLoad = 'FrmEmpresaEstado', GrupoOpciones = 'OficinaCentral', IdOrden = 5, RutaCompleta = '1|18|23', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 23
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 24 )  Insert Into Net_Navegacion Values ( 'CFGN', 24, 'Tipo de Cambio de Dollar', 18, 'FrmTipoDeCambio', 'Configuracion', 13, '1|18|24', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Tipo de Cambio de Dollar', Padre = 18, FormaLoad = 'FrmTipoDeCambio', GrupoOpciones = 'Configuracion', IdOrden = 13, RutaCompleta = '1|18|24', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 24
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 25 )  Insert Into Net_Navegacion Values ( 'CFGN', 25, 'Almacen Jurisdiccional', 18, '', '', 1, '1|18|25', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Almacen Jurisdiccional', Padre = 18, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|18|25', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 25
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 26 )  Insert Into Net_Navegacion Values ( 'CFGN', 26, 'Configurar Unidades de Almacen', 25, 'FrmConfigUnidadesALMJ', 'Configuracion', 1, '1|18|25|26', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar Unidades de Almacen', Padre = 25, FormaLoad = 'FrmConfigUnidadesALMJ', GrupoOpciones = 'Configuracion', IdOrden = 1, RutaCompleta = '1|18|25|26', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 26
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 27 )  Insert Into Net_Navegacion Values ( 'CFGN', 27, 'Permisos especiales', 15, 'FrmPermisosOperacionesSupervizadas', 'Configuracion', 9, '1|15|27', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Permisos especiales', Padre = 15, FormaLoad = 'FrmPermisosOperacionesSupervizadas', GrupoOpciones = 'Configuracion', IdOrden = 9, RutaCompleta = '1|15|27', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 27
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 28 )  Insert Into Net_Navegacion Values ( 'CFGN', 28, 'Operaciones Especiales', 15, 'FrmOperacionesSupervizadas', 'Configuracion', 7, '1|15|28', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Operaciones Especiales', Padre = 15, FormaLoad = 'FrmOperacionesSupervizadas', GrupoOpciones = 'Configuracion', IdOrden = 7, RutaCompleta = '1|15|28', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 28
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 29 )  Insert Into Net_Navegacion Values ( 'CFGN', 29, 'Acceso a Proveedores', 18, '', '', 3, '1|18|29', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Acceso a Proveedores', Padre = 18, FormaLoad = '', GrupoOpciones = '', IdOrden = 3, RutaCompleta = '1|18|29', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 29
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 30 )  Insert Into Net_Navegacion Values ( 'CFGN', 30, 'Configurar usuario', 29, 'FrmCfgAccesoProveedores', 'DllFarmaciaSoft', 1, '1|18|29|30', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar usuario', Padre = 29, FormaLoad = 'FrmCfgAccesoProveedores', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 1, RutaCompleta = '1|18|29|30', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 30
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 31 )  Insert Into Net_Navegacion Values ( 'CFGN', 31, 'IMatch', 1, '', '', 7, '1|31', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'IMatch', Padre = 1, FormaLoad = '', GrupoOpciones = '', IdOrden = 7, RutaCompleta = '1|31', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 31
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 32 )  Insert Into Net_Navegacion Values ( 'CFGN', 32, 'Registro', 31, '', '', 1, '1|31|32', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Registro', Padre = 31, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|31|32', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 32
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 33 )  Insert Into Net_Navegacion Values ( 'CFGN', 33, 'Clientes', 32, 'FrmClientes', 'Dll_IMach4', 1, '1|31|32|33', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Clientes', Padre = 32, FormaLoad = 'FrmClientes', GrupoOpciones = 'Dll_IMach4', IdOrden = 1, RutaCompleta = '1|31|32|33', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 33
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 34 )  Insert Into Net_Navegacion Values ( 'CFGN', 34, 'Terminales', 32, 'FrmTerminales', 'Dll_IMach4', 3, '1|31|32|34', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Terminales', Padre = 32, FormaLoad = 'FrmTerminales', GrupoOpciones = 'Dll_IMach4', IdOrden = 3, RutaCompleta = '1|31|32|34', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 34
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 35 )  Insert Into Net_Navegacion Values ( 'CFGN', 35, 'Configuración', 31, '', '', 3, '1|31|35', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configuración', Padre = 31, FormaLoad = '', GrupoOpciones = '', IdOrden = 3, RutaCompleta = '1|31|35', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 35
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 36 )  Insert Into Net_Navegacion Values ( 'CFGN', 36, 'Terminales por Cliente', 35, 'FrmClientesTerminales', 'Dll_IMach4', 1, '1|31|35|36', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Terminales por Cliente', Padre = 35, FormaLoad = 'FrmClientesTerminales', GrupoOpciones = 'Dll_IMach4', IdOrden = 1, RutaCompleta = '1|31|35|36', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 36
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 37 )  Insert Into Net_Navegacion Values ( 'CFGN', 37, 'Productos por Cliente', 35, 'FrmProductosClientes', 'Dll_IMach4', 1, '1|31|35|37', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Productos por Cliente', Padre = 35, FormaLoad = 'FrmProductosClientes', GrupoOpciones = 'Dll_IMach4', IdOrden = 1, RutaCompleta = '1|31|35|37', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 37
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 38 )  Insert Into Net_Navegacion Values ( 'CFGN', 38, 'Acceso a Clientes Regionales y Unidades', 18, '', '', 5, '1|18|38', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Acceso a Clientes Regionales y Unidades', Padre = 18, FormaLoad = '', GrupoOpciones = '', IdOrden = 5, RutaCompleta = '1|18|38', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 38
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 39 )  Insert Into Net_Navegacion Values ( 'CFGN', 39, 'Acceso Clientes Regionales', 38, 'FrmUsuariosClientesRegional', 'DllFarmaciaSoft', 1, '1|18|38|39', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Acceso Clientes Regionales', Padre = 38, FormaLoad = 'FrmUsuariosClientesRegional', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 1, RutaCompleta = '1|18|38|39', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 39
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 40 )  Insert Into Net_Navegacion Values ( 'CFGN', 40, 'Acceso Clientes Unidades', 38, 'FrmUsuariosClientesUnidad', 'DllFarmaciaSoft', 3, '1|18|38|40', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Acceso Clientes Unidades', Padre = 38, FormaLoad = 'FrmUsuariosClientesUnidad', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 3, RutaCompleta = '1|18|38|40', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 40
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 41 )  Insert Into Net_Navegacion Values ( 'CFGN', 41, 'Registro de Unidades a Administrar por Servidor', 18, 'FrmConfigurarUnidadesFarmacia', 'Configuracion', 1, '1|18|41', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Registro de Unidades a Administrar por Servidor', Padre = 18, FormaLoad = 'FrmConfigurarUnidadesFarmacia', GrupoOpciones = 'Configuracion', IdOrden = 1, RutaCompleta = '1|18|41', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 41
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 42 )  Insert Into Net_Navegacion Values ( 'CFGN', 42, 'Terminales registradas en Unidad', 18, 'FrmTerminales', 'Configuracion', 3, '1|18|42', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Terminales registradas en Unidad', Padre = 18, FormaLoad = 'FrmTerminales', GrupoOpciones = 'Configuracion', IdOrden = 3, RutaCompleta = '1|18|42', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 42
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 43 )  Insert Into Net_Navegacion Values ( 'CFGN', 43, 'Unidades', 6, '', '', 1, '1|6|43', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Unidades', Padre = 6, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|6|43', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 43
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGN' and Rama = 44 )  Insert Into Net_Navegacion Values ( 'CFGN', 44, 'Sub-Farmacias Estatales', 43, 'FrmSubFarmacias', 'OficinaCentral', 2, '1|6|43|44', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Sub-Farmacias Estatales', Padre = 43, FormaLoad = 'FrmSubFarmacias', GrupoOpciones = 'OficinaCentral', IdOrden = 2, RutaCompleta = '1|6|43|44', Status = 'A', Actualizado = 1 Where Arbol = 'CFGN' and Rama = 44
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 1 )  Insert Into Net_Navegacion Values ( 'CFGR', 1, 'Configuración Sitio Central Regional', -1, '', '', 0, '1', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configuración Sitio Central Regional', Padre = -1, FormaLoad = '', GrupoOpciones = '', IdOrden = 0, RutaCompleta = '1', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 1
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 2 )  Insert Into Net_Navegacion Values ( 'CFGR', 2, 'Configurar integración', 1, 'FrmConfigIntegrarInformacion', 'DllTransferenciaSoft', 1, '1|2', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar integración', Padre = 1, FormaLoad = 'FrmConfigIntegrarInformacion', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 1, RutaCompleta = '1|2', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 2
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 3 )  Insert Into Net_Navegacion Values ( 'CFGR', 3, 'Configurar obtención de información', 1, 'FrmConfigObtenerInformacion', 'DllTransferenciaSoft', 3, '1|3', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar obtención de información', Padre = 1, FormaLoad = 'FrmConfigObtenerInformacion', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 3, RutaCompleta = '1|3', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 3
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 4 )  Insert Into Net_Navegacion Values ( 'CFGR', 4, 'Configurar conexión con Sitio Central', 1, 'FrmConfigurarConexionOficinaCentral', 'DllTransferenciaSoft', 5, '1|4', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar conexión con Sitio Central', Padre = 1, FormaLoad = 'FrmConfigurarConexionOficinaCentral', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 5, RutaCompleta = '1|4', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 4
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 5 )  Insert Into Net_Navegacion Values ( 'CFGR', 5, 'Configurar respaldo de base de datos', 1, 'FrmConfigRespaldosBD', 'DllTransferenciaSoft', 9, '1|5', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar respaldo de base de datos', Padre = 1, FormaLoad = 'FrmConfigRespaldosBD', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 9, RutaCompleta = '1|5', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 5
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 6 )  Insert Into Net_Navegacion Values ( 'CFGR', 6, 'Configurar conexiones con Puntos de venta', 1, 'FrmConfigurarConexionClientes', 'DllTransferenciaSoft', 7, '1|6', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar conexiones con Puntos de venta', Padre = 1, FormaLoad = 'FrmConfigurarConexionClientes', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 7, RutaCompleta = '1|6', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 6
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 7 )  Insert Into Net_Navegacion Values ( 'CFGR', 7, 'Auditoria', 1, '', '', 1, '1|7', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Auditoria', Padre = 1, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|7', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 7
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 8 )  Insert Into Net_Navegacion Values ( 'CFGR', 8, 'Registros', 7, 'FrmMovtosUnidades', 'DllTransferenciaSoft', 3, '1|7|8', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Registros', Padre = 7, FormaLoad = 'FrmMovtosUnidades', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 3, RutaCompleta = '1|7|8', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 8
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 9 )  Insert Into Net_Navegacion Values ( 'CFGR', 9, 'Fechas de Sistema y Servidor', 7, 'FrmFechasUnidades', 'DllTransferenciaSoft', 5, '1|7|9', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Fechas de Sistema y Servidor', Padre = 7, FormaLoad = 'FrmFechasUnidades', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 5, RutaCompleta = '1|7|9', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 9
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 10 )  Insert Into Net_Navegacion Values ( 'CFGR', 10, 'Versiones SII instaladas', 7, 'FrmVersionesSII', 'DllTransferenciaSoft', 1, '1|7|10', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Versiones SII instaladas', Padre = 7, FormaLoad = 'FrmVersionesSII', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 1, RutaCompleta = '1|7|10', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 10
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGR' and Rama = 11 )  Insert Into Net_Navegacion Values ( 'CFGR', 11, 'Información de Unidades en Regional', 7, 'FrmInfoUnidadesVsRegional', 'DllTransferenciaSoft', 7, '1|7|11', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Información de Unidades en Regional', Padre = 7, FormaLoad = 'FrmInfoUnidadesVsRegional', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 7, RutaCompleta = '1|7|11', Status = 'A', Actualizado = 1 Where Arbol = 'CFGR' and Rama = 11
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGS' and Rama = 1 )  Insert Into Net_Navegacion Values ( 'CFGS', 1, 'Configuración Sitio Central', -1, '', '', 0, '1', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configuración Sitio Central', Padre = -1, FormaLoad = '', GrupoOpciones = '', IdOrden = 0, RutaCompleta = '1', Status = 'A', Actualizado = 1 Where Arbol = 'CFGS' and Rama = 1
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGS' and Rama = 2 )  Insert Into Net_Navegacion Values ( 'CFGS', 2, 'Configurar integración', 1, 'FrmConfigIntegrarInformacion', 'DllTransferenciaSoft', 1, '1|2', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar integración', Padre = 1, FormaLoad = 'FrmConfigIntegrarInformacion', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 1, RutaCompleta = '1|2', Status = 'A', Actualizado = 1 Where Arbol = 'CFGS' and Rama = 2
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGS' and Rama = 3 )  Insert Into Net_Navegacion Values ( 'CFGS', 3, 'Configurar obtención de información', 1, 'FrmConfigObtenerInformacion', 'DllTransferenciaSoft', 3, '1|3', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar obtención de información', Padre = 1, FormaLoad = 'FrmConfigObtenerInformacion', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 3, RutaCompleta = '1|3', Status = 'A', Actualizado = 1 Where Arbol = 'CFGS' and Rama = 3
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGS' and Rama = 4 )  Insert Into Net_Navegacion Values ( 'CFGS', 4, 'Configurar conexiones con Servidores Regionales', 1, 'FrmConfigurarConexionClientesRegionales', 'DllTransferenciaSoft', 5, '1|4', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar conexiones con Servidores Regionales', Padre = 1, FormaLoad = 'FrmConfigurarConexionClientesRegionales', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 5, RutaCompleta = '1|4', Status = 'A', Actualizado = 1 Where Arbol = 'CFGS' and Rama = 4
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGS' and Rama = 5 )  Insert Into Net_Navegacion Values ( 'CFGS', 5, 'Configurar respaldo de base de datos', 1, 'FrmConfigRespaldosBD', 'DllTransferenciaSoft', 7, '1|5', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Configurar respaldo de base de datos', Padre = 1, FormaLoad = 'FrmConfigRespaldosBD', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 7, RutaCompleta = '1|5', Status = 'A', Actualizado = 1 Where Arbol = 'CFGS' and Rama = 5
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGS' and Rama = 6 )  Insert Into Net_Navegacion Values ( 'CFGS', 6, 'Auditoria', 1, '', '', 1, '1|6', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Auditoria', Padre = 1, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|6', Status = 'A', Actualizado = 1 Where Arbol = 'CFGS' and Rama = 6
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGS' and Rama = 7 )  Insert Into Net_Navegacion Values ( 'CFGS', 7, 'Versiones SII instaladas', 6, 'FrmVersionesSII', 'DllTransferenciaSoft', 3, '1|6|7', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Versiones SII instaladas', Padre = 6, FormaLoad = 'FrmVersionesSII', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 3, RutaCompleta = '1|6|7', Status = 'A', Actualizado = 1 Where Arbol = 'CFGS' and Rama = 7
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'CFGS' and Rama = 8 )  Insert Into Net_Navegacion Values ( 'CFGS', 8, 'Versiones Regionales SII instaladas', 6, 'FrmVersionesRegionalesSII', 'DllTransferenciaSoft', 1, '1|6|8', 'A', 1 )    Else Update Net_Navegacion Set Nombre = 'Versiones Regionales SII instaladas', Padre = 6, FormaLoad = 'FrmVersionesRegionalesSII', GrupoOpciones = 'DllTransferenciaSoft', IdOrden = 1, RutaCompleta = '1|6|8', Status = 'A', Actualizado = 1 Where Arbol = 'CFGS' and Rama = 8 
Go--#SQL 
