//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Dll_ISESEQ.wsAcuseProcesos_cnnInterna {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsISESEQSoap", Namespace="http://SC-Solutions/ServiciosWeb/")]
    public partial class wsISESEQ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAcusesRecetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAcusesCancelacionRecetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecepcionDeRecetaElectronicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DescargarInventarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcuseSurtidoDeRecetaElectronicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarFirmaDeEntregaColectivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcuseDigitalizacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelacionDeRecetaElectronicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcuseDeCancelacionDeRecetaElectronicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarInformacionOperacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsISESEQ() {
            this.Url = "http://localhost:3000/wsISESEQ.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAcusesRecetaCompletedEventHandler GetAcusesRecetaCompleted;
        
        /// <remarks/>
        public event GetAcusesCancelacionRecetaCompletedEventHandler GetAcusesCancelacionRecetaCompleted;
        
        /// <remarks/>
        public event RecepcionDeRecetaElectronicaCompletedEventHandler RecepcionDeRecetaElectronicaCompleted;
        
        /// <remarks/>
        public event DescargarInventarioCompletedEventHandler DescargarInventarioCompleted;
        
        /// <remarks/>
        public event AcuseSurtidoDeRecetaElectronicaCompletedEventHandler AcuseSurtidoDeRecetaElectronicaCompleted;
        
        /// <remarks/>
        public event ValidarFirmaDeEntregaColectivoCompletedEventHandler ValidarFirmaDeEntregaColectivoCompleted;
        
        /// <remarks/>
        public event AcuseDigitalizacionCompletedEventHandler AcuseDigitalizacionCompleted;
        
        /// <remarks/>
        public event CancelacionDeRecetaElectronicaCompletedEventHandler CancelacionDeRecetaElectronicaCompleted;
        
        /// <remarks/>
        public event AcuseDeCancelacionDeRecetaElectronicaCompletedEventHandler AcuseDeCancelacionDeRecetaElectronicaCompleted;
        
        /// <remarks/>
        public event EnviarInformacionOperacionCompletedEventHandler EnviarInformacionOperacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/GetAcusesReceta", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAcusesReceta(string IdEmpresa, string IdEstado, string IdFarmacia, int EnviarXML) {
            object[] results = this.Invoke("GetAcusesReceta", new object[] {
                        IdEmpresa,
                        IdEstado,
                        IdFarmacia,
                        EnviarXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAcusesRecetaAsync(string IdEmpresa, string IdEstado, string IdFarmacia, int EnviarXML) {
            this.GetAcusesRecetaAsync(IdEmpresa, IdEstado, IdFarmacia, EnviarXML, null);
        }
        
        /// <remarks/>
        public void GetAcusesRecetaAsync(string IdEmpresa, string IdEstado, string IdFarmacia, int EnviarXML, object userState) {
            if ((this.GetAcusesRecetaOperationCompleted == null)) {
                this.GetAcusesRecetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAcusesRecetaOperationCompleted);
            }
            this.InvokeAsync("GetAcusesReceta", new object[] {
                        IdEmpresa,
                        IdEstado,
                        IdFarmacia,
                        EnviarXML}, this.GetAcusesRecetaOperationCompleted, userState);
        }
        
        private void OnGetAcusesRecetaOperationCompleted(object arg) {
            if ((this.GetAcusesRecetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAcusesRecetaCompleted(this, new GetAcusesRecetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/GetAcusesCancelacionReceta", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAcusesCancelacionReceta(string IdEmpresa, string IdEstado, string IdFarmacia, int EnviarXML) {
            object[] results = this.Invoke("GetAcusesCancelacionReceta", new object[] {
                        IdEmpresa,
                        IdEstado,
                        IdFarmacia,
                        EnviarXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAcusesCancelacionRecetaAsync(string IdEmpresa, string IdEstado, string IdFarmacia, int EnviarXML) {
            this.GetAcusesCancelacionRecetaAsync(IdEmpresa, IdEstado, IdFarmacia, EnviarXML, null);
        }
        
        /// <remarks/>
        public void GetAcusesCancelacionRecetaAsync(string IdEmpresa, string IdEstado, string IdFarmacia, int EnviarXML, object userState) {
            if ((this.GetAcusesCancelacionRecetaOperationCompleted == null)) {
                this.GetAcusesCancelacionRecetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAcusesCancelacionRecetaOperationCompleted);
            }
            this.InvokeAsync("GetAcusesCancelacionReceta", new object[] {
                        IdEmpresa,
                        IdEstado,
                        IdFarmacia,
                        EnviarXML}, this.GetAcusesCancelacionRecetaOperationCompleted, userState);
        }
        
        private void OnGetAcusesCancelacionRecetaOperationCompleted(object arg) {
            if ((this.GetAcusesCancelacionRecetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAcusesCancelacionRecetaCompleted(this, new GetAcusesCancelacionRecetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/RecepcionDeRecetaElectronica", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecepcionDeRecetaElectronica(string Informacion_XML, string GUID) {
            object[] results = this.Invoke("RecepcionDeRecetaElectronica", new object[] {
                        Informacion_XML,
                        GUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecepcionDeRecetaElectronicaAsync(string Informacion_XML, string GUID) {
            this.RecepcionDeRecetaElectronicaAsync(Informacion_XML, GUID, null);
        }
        
        /// <remarks/>
        public void RecepcionDeRecetaElectronicaAsync(string Informacion_XML, string GUID, object userState) {
            if ((this.RecepcionDeRecetaElectronicaOperationCompleted == null)) {
                this.RecepcionDeRecetaElectronicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecepcionDeRecetaElectronicaOperationCompleted);
            }
            this.InvokeAsync("RecepcionDeRecetaElectronica", new object[] {
                        Informacion_XML,
                        GUID}, this.RecepcionDeRecetaElectronicaOperationCompleted, userState);
        }
        
        private void OnRecepcionDeRecetaElectronicaOperationCompleted(object arg) {
            if ((this.RecepcionDeRecetaElectronicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecepcionDeRecetaElectronicaCompleted(this, new RecepcionDeRecetaElectronicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/DescargarInventario", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DescargarInventario(string Informacion_XML, string GUID, int TipoUnidad) {
            object[] results = this.Invoke("DescargarInventario", new object[] {
                        Informacion_XML,
                        GUID,
                        TipoUnidad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DescargarInventarioAsync(string Informacion_XML, string GUID, int TipoUnidad) {
            this.DescargarInventarioAsync(Informacion_XML, GUID, TipoUnidad, null);
        }
        
        /// <remarks/>
        public void DescargarInventarioAsync(string Informacion_XML, string GUID, int TipoUnidad, object userState) {
            if ((this.DescargarInventarioOperationCompleted == null)) {
                this.DescargarInventarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDescargarInventarioOperationCompleted);
            }
            this.InvokeAsync("DescargarInventario", new object[] {
                        Informacion_XML,
                        GUID,
                        TipoUnidad}, this.DescargarInventarioOperationCompleted, userState);
        }
        
        private void OnDescargarInventarioOperationCompleted(object arg) {
            if ((this.DescargarInventarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DescargarInventarioCompleted(this, new DescargarInventarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/AcuseSurtidoDeRecetaElectronica", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AcuseSurtidoDeRecetaElectronica(string Informacion_XML) {
            object[] results = this.Invoke("AcuseSurtidoDeRecetaElectronica", new object[] {
                        Informacion_XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AcuseSurtidoDeRecetaElectronicaAsync(string Informacion_XML) {
            this.AcuseSurtidoDeRecetaElectronicaAsync(Informacion_XML, null);
        }
        
        /// <remarks/>
        public void AcuseSurtidoDeRecetaElectronicaAsync(string Informacion_XML, object userState) {
            if ((this.AcuseSurtidoDeRecetaElectronicaOperationCompleted == null)) {
                this.AcuseSurtidoDeRecetaElectronicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcuseSurtidoDeRecetaElectronicaOperationCompleted);
            }
            this.InvokeAsync("AcuseSurtidoDeRecetaElectronica", new object[] {
                        Informacion_XML}, this.AcuseSurtidoDeRecetaElectronicaOperationCompleted, userState);
        }
        
        private void OnAcuseSurtidoDeRecetaElectronicaOperationCompleted(object arg) {
            if ((this.AcuseSurtidoDeRecetaElectronicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcuseSurtidoDeRecetaElectronicaCompleted(this, new AcuseSurtidoDeRecetaElectronicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/ValidarFirmaDeEntregaColectivo", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidarFirmaDeEntregaColectivo(string Folio, string Firma) {
            object[] results = this.Invoke("ValidarFirmaDeEntregaColectivo", new object[] {
                        Folio,
                        Firma});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarFirmaDeEntregaColectivoAsync(string Folio, string Firma) {
            this.ValidarFirmaDeEntregaColectivoAsync(Folio, Firma, null);
        }
        
        /// <remarks/>
        public void ValidarFirmaDeEntregaColectivoAsync(string Folio, string Firma, object userState) {
            if ((this.ValidarFirmaDeEntregaColectivoOperationCompleted == null)) {
                this.ValidarFirmaDeEntregaColectivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarFirmaDeEntregaColectivoOperationCompleted);
            }
            this.InvokeAsync("ValidarFirmaDeEntregaColectivo", new object[] {
                        Folio,
                        Firma}, this.ValidarFirmaDeEntregaColectivoOperationCompleted, userState);
        }
        
        private void OnValidarFirmaDeEntregaColectivoOperationCompleted(object arg) {
            if ((this.ValidarFirmaDeEntregaColectivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarFirmaDeEntregaColectivoCompleted(this, new ValidarFirmaDeEntregaColectivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/AcuseDigitalizacion", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AcuseDigitalizacion(string Informacion_XML) {
            object[] results = this.Invoke("AcuseDigitalizacion", new object[] {
                        Informacion_XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AcuseDigitalizacionAsync(string Informacion_XML) {
            this.AcuseDigitalizacionAsync(Informacion_XML, null);
        }
        
        /// <remarks/>
        public void AcuseDigitalizacionAsync(string Informacion_XML, object userState) {
            if ((this.AcuseDigitalizacionOperationCompleted == null)) {
                this.AcuseDigitalizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcuseDigitalizacionOperationCompleted);
            }
            this.InvokeAsync("AcuseDigitalizacion", new object[] {
                        Informacion_XML}, this.AcuseDigitalizacionOperationCompleted, userState);
        }
        
        private void OnAcuseDigitalizacionOperationCompleted(object arg) {
            if ((this.AcuseDigitalizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcuseDigitalizacionCompleted(this, new AcuseDigitalizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/CancelacionDeRecetaElectronica", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelacionDeRecetaElectronica(string Informacion_XML, string GUID) {
            object[] results = this.Invoke("CancelacionDeRecetaElectronica", new object[] {
                        Informacion_XML,
                        GUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelacionDeRecetaElectronicaAsync(string Informacion_XML, string GUID) {
            this.CancelacionDeRecetaElectronicaAsync(Informacion_XML, GUID, null);
        }
        
        /// <remarks/>
        public void CancelacionDeRecetaElectronicaAsync(string Informacion_XML, string GUID, object userState) {
            if ((this.CancelacionDeRecetaElectronicaOperationCompleted == null)) {
                this.CancelacionDeRecetaElectronicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelacionDeRecetaElectronicaOperationCompleted);
            }
            this.InvokeAsync("CancelacionDeRecetaElectronica", new object[] {
                        Informacion_XML,
                        GUID}, this.CancelacionDeRecetaElectronicaOperationCompleted, userState);
        }
        
        private void OnCancelacionDeRecetaElectronicaOperationCompleted(object arg) {
            if ((this.CancelacionDeRecetaElectronicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelacionDeRecetaElectronicaCompleted(this, new CancelacionDeRecetaElectronicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/AcuseDeCancelacionDeRecetaElectronica", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AcuseDeCancelacionDeRecetaElectronica(string Informacion_XML) {
            object[] results = this.Invoke("AcuseDeCancelacionDeRecetaElectronica", new object[] {
                        Informacion_XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AcuseDeCancelacionDeRecetaElectronicaAsync(string Informacion_XML) {
            this.AcuseDeCancelacionDeRecetaElectronicaAsync(Informacion_XML, null);
        }
        
        /// <remarks/>
        public void AcuseDeCancelacionDeRecetaElectronicaAsync(string Informacion_XML, object userState) {
            if ((this.AcuseDeCancelacionDeRecetaElectronicaOperationCompleted == null)) {
                this.AcuseDeCancelacionDeRecetaElectronicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcuseDeCancelacionDeRecetaElectronicaOperationCompleted);
            }
            this.InvokeAsync("AcuseDeCancelacionDeRecetaElectronica", new object[] {
                        Informacion_XML}, this.AcuseDeCancelacionDeRecetaElectronicaOperationCompleted, userState);
        }
        
        private void OnAcuseDeCancelacionDeRecetaElectronicaOperationCompleted(object arg) {
            if ((this.AcuseDeCancelacionDeRecetaElectronicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcuseDeCancelacionDeRecetaElectronicaCompleted(this, new AcuseDeCancelacionDeRecetaElectronicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SC-Solutions/ServiciosWeb/EnviarInformacionOperacion", RequestNamespace="http://SC-Solutions/ServiciosWeb/", ResponseNamespace="http://SC-Solutions/ServiciosWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarInformacionOperacion(string Informacion_XML, string GUID) {
            object[] results = this.Invoke("EnviarInformacionOperacion", new object[] {
                        Informacion_XML,
                        GUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarInformacionOperacionAsync(string Informacion_XML, string GUID) {
            this.EnviarInformacionOperacionAsync(Informacion_XML, GUID, null);
        }
        
        /// <remarks/>
        public void EnviarInformacionOperacionAsync(string Informacion_XML, string GUID, object userState) {
            if ((this.EnviarInformacionOperacionOperationCompleted == null)) {
                this.EnviarInformacionOperacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarInformacionOperacionOperationCompleted);
            }
            this.InvokeAsync("EnviarInformacionOperacion", new object[] {
                        Informacion_XML,
                        GUID}, this.EnviarInformacionOperacionOperationCompleted, userState);
        }
        
        private void OnEnviarInformacionOperacionOperationCompleted(object arg) {
            if ((this.EnviarInformacionOperacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarInformacionOperacionCompleted(this, new EnviarInformacionOperacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAcusesRecetaCompletedEventHandler(object sender, GetAcusesRecetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAcusesRecetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAcusesRecetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAcusesCancelacionRecetaCompletedEventHandler(object sender, GetAcusesCancelacionRecetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAcusesCancelacionRecetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAcusesCancelacionRecetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RecepcionDeRecetaElectronicaCompletedEventHandler(object sender, RecepcionDeRecetaElectronicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecepcionDeRecetaElectronicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecepcionDeRecetaElectronicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DescargarInventarioCompletedEventHandler(object sender, DescargarInventarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DescargarInventarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DescargarInventarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AcuseSurtidoDeRecetaElectronicaCompletedEventHandler(object sender, AcuseSurtidoDeRecetaElectronicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcuseSurtidoDeRecetaElectronicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcuseSurtidoDeRecetaElectronicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidarFirmaDeEntregaColectivoCompletedEventHandler(object sender, ValidarFirmaDeEntregaColectivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarFirmaDeEntregaColectivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarFirmaDeEntregaColectivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AcuseDigitalizacionCompletedEventHandler(object sender, AcuseDigitalizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcuseDigitalizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcuseDigitalizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CancelacionDeRecetaElectronicaCompletedEventHandler(object sender, CancelacionDeRecetaElectronicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelacionDeRecetaElectronicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelacionDeRecetaElectronicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AcuseDeCancelacionDeRecetaElectronicaCompletedEventHandler(object sender, AcuseDeCancelacionDeRecetaElectronicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcuseDeCancelacionDeRecetaElectronicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcuseDeCancelacionDeRecetaElectronicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EnviarInformacionOperacionCompletedEventHandler(object sender, EnviarInformacionOperacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarInformacionOperacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarInformacionOperacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591