//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dll_INT_CNNSIADISSEP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:21734/wsSII_INT_ISIADISSEP/wsISIADISSEP.asmx")]
        public string Dll_INT_CNNSIADISSEP_ws_Interface_SII_SIADISSEP_wsISIADISSEP {
            get {
                return ((string)(this["Dll_INT_CNNSIADISSEP_ws_Interface_SII_SIADISSEP_wsISIADISSEP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ec2-54-188-66-44.us-west-2.compute.amazonaws.com:8090/WsPrueba/WsPrueba")]
        public string Dll_INT_CNNSIADISSEP_wsRecetaElectronica_SSEP_WsPrueba {
            get {
                return ((string)(this["Dll_INT_CNNSIADISSEP_wsRecetaElectronica_SSEP_WsPrueba"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ec2-54-244-200-58.us-west-2.compute.amazonaws.com:8090/Polux/services/Reci" +
            "eveXML")]
        public string Dll_INT_CNNSIADISSEP_wsRecetaElectronica_SSEP__20_RecieveXMLService {
            get {
                return ((string)(this["Dll_INT_CNNSIADISSEP_wsRecetaElectronica_SSEP__20_RecieveXMLService"]));
            }
        }
    }
}
