Set NoCount On 
Go--#SQL 

If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 1 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 1, 'Facturación', -1, '', '', 0, '1', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Facturación', Padre = -1, FormaLoad = '', GrupoOpciones = '', IdOrden = 0, RutaCompleta = '1', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 1  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 2 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 2, 'Configuraciones', 1, '', '', 1, '1|2', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Configuraciones', Padre = 1, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|2', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 2  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 3 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 3, 'Facturacion', 1, '', '', 2, '1|3', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Facturacion', Padre = 1, FormaLoad = '', GrupoOpciones = '', IdOrden = 2, RutaCompleta = '1|3', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 3  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 4 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 4, 'Asignación de Claves SSA', 2, '', '', 1, '1|2|4', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Asignación de Claves SSA', Padre = 2, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|2|4', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 4  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 5 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 5, 'Asignación de Precios', 2, '', '', 2, '1|2|5', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Asignación de Precios', Padre = 2, FormaLoad = '', GrupoOpciones = '', IdOrden = 2, RutaCompleta = '1|2|5', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 5  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 6 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 6, 'Perfiles de Claves (Cuadros básicos)', 2, '', '', 3, '1|2|6', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Perfiles de Claves (Cuadros básicos)', Padre = 2, FormaLoad = '', GrupoOpciones = '', IdOrden = 3, RutaCompleta = '1|2|6', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 6  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 7 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 7, 'Procesos', 3, '', '', 1, '1|3|7', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Procesos', Padre = 3, FormaLoad = '', GrupoOpciones = '', IdOrden = 1, RutaCompleta = '1|3|7', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 7  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 8 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 8, 'Reportes', 3, '', '', 2, '1|3|8', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Reportes', Padre = 3, FormaLoad = '', GrupoOpciones = '', IdOrden = 2, RutaCompleta = '1|3|8', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 8  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 9 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 9, 'Claves SSA por Cliente', 4, 'FrmClientesClavesSSA', 'OficinaCentral', 1, '1|2|4|9', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Claves SSA por Cliente', Padre = 4, FormaLoad = 'FrmClientesClavesSSA', GrupoOpciones = 'OficinaCentral', IdOrden = 1, RutaCompleta = '1|2|4|9', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 9  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 10 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 10, 'Claves SSA por Sub-Cliente', 4, 'FrmClientesSubClientesClavesSSA', 'OficinaCentral', 2, '1|2|4|10', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Claves SSA por Sub-Cliente', Padre = 4, FormaLoad = 'FrmClientesSubClientesClavesSSA', GrupoOpciones = 'OficinaCentral', IdOrden = 2, RutaCompleta = '1|2|4|10', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 10  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 11 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 11, 'Asignar Precio a Claves SSA', 5, 'FrmPreciosClavesSSA', 'OficinaCentral', 1, '1|2|5|11', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Asignar Precio a Claves SSA', Padre = 5, FormaLoad = 'FrmPreciosClavesSSA', GrupoOpciones = 'OficinaCentral', IdOrden = 1, RutaCompleta = '1|2|5|11', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 11  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 12 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 12, 'Perfil', 6, 'FrmNivelesAtencion', 'OficinaCentral', 1, '1|2|6|12', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Perfil', Padre = 6, FormaLoad = 'FrmNivelesAtencion', GrupoOpciones = 'OficinaCentral', IdOrden = 1, RutaCompleta = '1|2|6|12', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 12  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 13 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 13, 'Claves de Perfil', 6, 'FrmCuadrosBasicos', 'OficinaCentral', 2, '1|2|6|13', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Claves de Perfil', Padre = 6, FormaLoad = 'FrmCuadrosBasicos', GrupoOpciones = 'OficinaCentral', IdOrden = 2, RutaCompleta = '1|2|6|13', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 13  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 14 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 14, 'Claves excluidas de Abasto', 6, 'FrmClavesExcluidasAbasto', 'OficinaCentral', 3, '1|2|6|14', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Claves excluidas de Abasto', Padre = 6, FormaLoad = 'FrmClavesExcluidasAbasto', GrupoOpciones = 'OficinaCentral', IdOrden = 3, RutaCompleta = '1|2|6|14', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 14  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 15 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 15, 'Cierre de periodos para facturación', 7, 'FrmCierrePeriodoCentral', 'DllFarmaciaSoft', 1, '1|3|7|15', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Cierre de periodos para facturación', Padre = 7, FormaLoad = 'FrmCierrePeriodoCentral', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 1, RutaCompleta = '1|3|7|15', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 15  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 16 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 16, 'Listados de cierres de facturación', 7, 'FrmListadoCierresFacturacion', 'DllFarmaciaSoft', 2, '1|3|7|16', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Listados de cierres de facturación', Padre = 7, FormaLoad = 'FrmListadoCierresFacturacion', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 2, RutaCompleta = '1|3|7|16', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 16  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 17 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 17, 'Reportes de Validación y Facturacion', 8, 'FrmReportesFacturacion', 'DllFarmaciaSoft', 1, '1|3|8|17', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Reportes de Validación y Facturacion', Padre = 8, FormaLoad = 'FrmReportesFacturacion', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 1, RutaCompleta = '1|3|8|17', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 17  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 18 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 18, 'Listado de Ventas por Cliente y Programas', 8, 'FrmReporteListadoCteProgramasVenta', 'DllFarmaciaSoft', 2, '1|3|8|18', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Listado de Ventas por Cliente y Programas', Padre = 8, FormaLoad = 'FrmReporteListadoCteProgramasVenta', GrupoOpciones = 'DllFarmaciaSoft', IdOrden = 2, RutaCompleta = '1|3|8|18', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 18  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 19 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 19, 'Relación de Clientes por Estado', 2, 'FrmEstadosClientes', 'OficinaCentral', 4, '1|2|19', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Relación de Clientes por Estado', Padre = 2, FormaLoad = 'FrmEstadosClientes', GrupoOpciones = 'OficinaCentral', IdOrden = 4, RutaCompleta = '1|2|19', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 19  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 20 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 20, 'Relación de Clientes por Farmacia', 2, 'FrmEstadosFarmaciasClientes', 'OficinaCentral', 5, '1|2|20', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Relación de Clientes por Farmacia', Padre = 2, FormaLoad = 'FrmEstadosFarmaciasClientes', GrupoOpciones = 'OficinaCentral', IdOrden = 5, RutaCompleta = '1|2|20', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 20  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 21 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 21, 'Relación de Programas por Cliente por Farmacia', 2, 'FrmEstadosFarmacias_ClientesProgramas', 'OficinaCentral', 6, '1|2|21', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Relación de Programas por Cliente por Farmacia', Padre = 2, FormaLoad = 'FrmEstadosFarmacias_ClientesProgramas', GrupoOpciones = 'OficinaCentral', IdOrden = 6, RutaCompleta = '1|2|21', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 21  
If Not Exists ( Select * From Net_Navegacion Where Arbol = 'FACT' and Rama = 22 )  Insert Into Net_Navegacion (  Arbol, Rama, Nombre, Padre, FormaLoad, GrupoOpciones, IdOrden, RutaCompleta, Status, Actualizado )  Values ( 'FACT', 22, 'Relación de Servicios y Areas por Farmacia', 2, 'FrmEstadosFarmacias_ServiciosAreas', 'OficinaCentral', 7, '1|2|22', 'A', 0 )    Else Update Net_Navegacion Set Nombre = 'Relación de Servicios y Areas por Farmacia', Padre = 2, FormaLoad = 'FrmEstadosFarmacias_ServiciosAreas', GrupoOpciones = 'OficinaCentral', IdOrden = 7, RutaCompleta = '1|2|22', Status = 'A', Actualizado = 0 Where Arbol = 'FACT' and Rama = 22   
Go--#SQL 

