//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DllTransferenciaSoft.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:31905/wsFarmaciaScSoft/wsFarmacia.asmx")]
        public string DllTransferenciaSoft_wsCliente_wsCnnCliente {
            get {
                return ((string)(this["DllTransferenciaSoft_wsCliente_wsCnnCliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:31905/wsFarmaciaScSoft/wsFarmaciaSoftGn.asmx")]
        public string DllTransferenciaSoft_wsFarmaciaSoftGn_wsConexion {
            get {
                return ((string)(this["DllTransferenciaSoft_wsFarmaciaSoftGn_wsConexion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:31905/wsFarmaciaScSoft/wsOficinaCentral.asmx")]
        public string DllTransferenciaSoft_wsOficinaCentral_wsCnnOficinaCentral {
            get {
                return ((string)(this["DllTransferenciaSoft_wsOficinaCentral_wsCnnOficinaCentral"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:31905/wsFarmaciaScSoft/wsOficinaCentralRegional.asmx")]
        public string DllTransferenciaSoft_wsOficinaCentralRegional_wsCnnOficinaCentralRegional {
            get {
                return ((string)(this["DllTransferenciaSoft_wsOficinaCentralRegional_wsCnnOficinaCentralRegional"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:31905/wsFarmaciaScSoft/wsClienteOficinaCentralRegional.asmx")]
        public string DllTransferenciaSoft_wsClienteOficinaCentralRegional_wsCnnClienteOficinaCentralRegional {
            get {
                return ((string)(this["DllTransferenciaSoft_wsClienteOficinaCentralRegional_wsCnnClienteOficinaCentralRe" +
                    "gional"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:31905/wsFarmaciaScSoft/wsHuellas.asmx")]
        public string DllTransferenciaSoft_wsInformacionHuellas_wsHuellas {
            get {
                return ((string)(this["DllTransferenciaSoft_wsInformacionHuellas_wsHuellas"]));
            }
        }
    }
}
