//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Dll_IFacturacion.PAC_VirtualSoft {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding", Namespace="http://tempuri.org/")]
    public partial class IService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbrarXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarXMLExternoOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificarVigenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback crearCuentaFOperationCompleted;
        
        private System.Threading.SendOrPostCallback crearCuentaF2OperationCompleted;
        
        private System.Threading.SendOrPostCallback agregarContribuyenteFOperationCompleted;
        
        private System.Threading.SendOrPostCallback quitarContribuyenteFOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerEstatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerRelacionadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback uuidsCancelacionPendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback aceptarRechazarCancelacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IService() {
            this.Url = global::Dll_IFacturacion.Properties.Settings.Default.Dll_IFacturacion_PAC_VirtualSoft_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event timbrarXMLCompletedEventHandler timbrarXMLCompleted;
        
        /// <remarks/>
        public event cancelarXMLCompletedEventHandler cancelarXMLCompleted;
        
        /// <remarks/>
        public event cancelarXMLExternoCompletedEventHandler cancelarXMLExternoCompleted;
        
        /// <remarks/>
        public event verificarVigenciaCompletedEventHandler verificarVigenciaCompleted;
        
        /// <remarks/>
        public event crearCuentaFCompletedEventHandler crearCuentaFCompleted;
        
        /// <remarks/>
        public event crearCuentaF2CompletedEventHandler crearCuentaF2Completed;
        
        /// <remarks/>
        public event agregarContribuyenteFCompletedEventHandler agregarContribuyenteFCompleted;
        
        /// <remarks/>
        public event quitarContribuyenteFCompletedEventHandler quitarContribuyenteFCompleted;
        
        /// <remarks/>
        public event obtenerXMLCompletedEventHandler obtenerXMLCompleted;
        
        /// <remarks/>
        public event obtenerEstatusCompletedEventHandler obtenerEstatusCompleted;
        
        /// <remarks/>
        public event obtenerRelacionadosCompletedEventHandler obtenerRelacionadosCompleted;
        
        /// <remarks/>
        public event uuidsCancelacionPendientesCompletedEventHandler uuidsCancelacionPendientesCompleted;
        
        /// <remarks/>
        public event aceptarRechazarCancelacionCompletedEventHandler aceptarRechazarCancelacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value) {
            object[] results = this.Invoke("GetData", new object[] {
                        value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value) {
            this.GetDataAsync(value, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/timbrarXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int timbrarXML([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string XMLOrigen, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string XMLDestino, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string MensajeError) {
            object[] results = this.Invoke("timbrarXML", new object[] {
                        idCuenta,
                        passwordCuenta,
                        XMLOrigen,
                        XMLDestino,
                        MensajeError});
            XMLDestino = ((string)(results[1]));
            MensajeError = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void timbrarXMLAsync(string idCuenta, string passwordCuenta, string XMLOrigen, string XMLDestino, string MensajeError) {
            this.timbrarXMLAsync(idCuenta, passwordCuenta, XMLOrigen, XMLDestino, MensajeError, null);
        }
        
        /// <remarks/>
        public void timbrarXMLAsync(string idCuenta, string passwordCuenta, string XMLOrigen, string XMLDestino, string MensajeError, object userState) {
            if ((this.timbrarXMLOperationCompleted == null)) {
                this.timbrarXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbrarXMLOperationCompleted);
            }
            this.InvokeAsync("timbrarXML", new object[] {
                        idCuenta,
                        passwordCuenta,
                        XMLOrigen,
                        XMLDestino,
                        MensajeError}, this.timbrarXMLOperationCompleted, userState);
        }
        
        private void OntimbrarXMLOperationCompleted(object arg) {
            if ((this.timbrarXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbrarXMLCompleted(this, new timbrarXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/cancelarXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int cancelarXML([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RFC, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sUUID, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] cer, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] key, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string motivo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string folioSustitucion, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string acuseRecibo) {
            object[] results = this.Invoke("cancelarXML", new object[] {
                        idCuenta,
                        passwordCuenta,
                        RFC,
                        sUUID,
                        cer,
                        key,
                        motivo,
                        folioSustitucion,
                        mensajeError,
                        acuseRecibo});
            mensajeError = ((string)(results[1]));
            acuseRecibo = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarXMLAsync(string idCuenta, string passwordCuenta, string RFC, string sUUID, byte[] cer, byte[] key, string motivo, string folioSustitucion, string mensajeError, string acuseRecibo) {
            this.cancelarXMLAsync(idCuenta, passwordCuenta, RFC, sUUID, cer, key, motivo, folioSustitucion, mensajeError, acuseRecibo, null);
        }
        
        /// <remarks/>
        public void cancelarXMLAsync(string idCuenta, string passwordCuenta, string RFC, string sUUID, byte[] cer, byte[] key, string motivo, string folioSustitucion, string mensajeError, string acuseRecibo, object userState) {
            if ((this.cancelarXMLOperationCompleted == null)) {
                this.cancelarXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarXMLOperationCompleted);
            }
            this.InvokeAsync("cancelarXML", new object[] {
                        idCuenta,
                        passwordCuenta,
                        RFC,
                        sUUID,
                        cer,
                        key,
                        motivo,
                        folioSustitucion,
                        mensajeError,
                        acuseRecibo}, this.cancelarXMLOperationCompleted, userState);
        }
        
        private void OncancelarXMLOperationCompleted(object arg) {
            if ((this.cancelarXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarXMLCompleted(this, new cancelarXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/cancelarXMLExterno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int cancelarXMLExterno([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RFCEmisor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RFCReceptor, double total, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sUUID, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] cer, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] key, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string motivo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string folioSustitucion, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string acuseRecibo) {
            object[] results = this.Invoke("cancelarXMLExterno", new object[] {
                        idCuenta,
                        passwordCuenta,
                        RFCEmisor,
                        RFCReceptor,
                        total,
                        sUUID,
                        cer,
                        key,
                        motivo,
                        folioSustitucion,
                        mensajeError,
                        acuseRecibo});
            mensajeError = ((string)(results[1]));
            acuseRecibo = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarXMLExternoAsync(string idCuenta, string passwordCuenta, string RFCEmisor, string RFCReceptor, double total, string sUUID, byte[] cer, byte[] key, string motivo, string folioSustitucion, string mensajeError, string acuseRecibo) {
            this.cancelarXMLExternoAsync(idCuenta, passwordCuenta, RFCEmisor, RFCReceptor, total, sUUID, cer, key, motivo, folioSustitucion, mensajeError, acuseRecibo, null);
        }
        
        /// <remarks/>
        public void cancelarXMLExternoAsync(string idCuenta, string passwordCuenta, string RFCEmisor, string RFCReceptor, double total, string sUUID, byte[] cer, byte[] key, string motivo, string folioSustitucion, string mensajeError, string acuseRecibo, object userState) {
            if ((this.cancelarXMLExternoOperationCompleted == null)) {
                this.cancelarXMLExternoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarXMLExternoOperationCompleted);
            }
            this.InvokeAsync("cancelarXMLExterno", new object[] {
                        idCuenta,
                        passwordCuenta,
                        RFCEmisor,
                        RFCReceptor,
                        total,
                        sUUID,
                        cer,
                        key,
                        motivo,
                        folioSustitucion,
                        mensajeError,
                        acuseRecibo}, this.cancelarXMLExternoOperationCompleted, userState);
        }
        
        private void OncancelarXMLExternoOperationCompleted(object arg) {
            if ((this.cancelarXMLExternoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarXMLExternoCompleted(this, new cancelarXMLExternoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/verificarVigencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int verificarVigencia([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string detallesLicencia, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("verificarVigencia", new object[] {
                        idCuenta,
                        passwordCuenta,
                        detallesLicencia,
                        mensajeError});
            detallesLicencia = ((string)(results[1]));
            mensajeError = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void verificarVigenciaAsync(string idCuenta, string passwordCuenta, string detallesLicencia, string mensajeError) {
            this.verificarVigenciaAsync(idCuenta, passwordCuenta, detallesLicencia, mensajeError, null);
        }
        
        /// <remarks/>
        public void verificarVigenciaAsync(string idCuenta, string passwordCuenta, string detallesLicencia, string mensajeError, object userState) {
            if ((this.verificarVigenciaOperationCompleted == null)) {
                this.verificarVigenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificarVigenciaOperationCompleted);
            }
            this.InvokeAsync("verificarVigencia", new object[] {
                        idCuenta,
                        passwordCuenta,
                        detallesLicencia,
                        mensajeError}, this.verificarVigenciaOperationCompleted, userState);
        }
        
        private void OnverificarVigenciaOperationCompleted(object arg) {
            if ((this.verificarVigenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificarVigenciaCompleted(this, new verificarVigenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/crearCuentaF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int crearCuentaF([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nombreEmpresa, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string razonSocial, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string correoElectronico, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("crearCuentaF", new object[] {
                        nombreEmpresa,
                        rfc,
                        razonSocial,
                        correoElectronico,
                        idCuenta,
                        passwordCuenta,
                        mensajeError});
            idCuenta = ((string)(results[1]));
            passwordCuenta = ((string)(results[2]));
            mensajeError = ((string)(results[3]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void crearCuentaFAsync(string nombreEmpresa, string rfc, string razonSocial, string correoElectronico, string idCuenta, string passwordCuenta, string mensajeError) {
            this.crearCuentaFAsync(nombreEmpresa, rfc, razonSocial, correoElectronico, idCuenta, passwordCuenta, mensajeError, null);
        }
        
        /// <remarks/>
        public void crearCuentaFAsync(string nombreEmpresa, string rfc, string razonSocial, string correoElectronico, string idCuenta, string passwordCuenta, string mensajeError, object userState) {
            if ((this.crearCuentaFOperationCompleted == null)) {
                this.crearCuentaFOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearCuentaFOperationCompleted);
            }
            this.InvokeAsync("crearCuentaF", new object[] {
                        nombreEmpresa,
                        rfc,
                        razonSocial,
                        correoElectronico,
                        idCuenta,
                        passwordCuenta,
                        mensajeError}, this.crearCuentaFOperationCompleted, userState);
        }
        
        private void OncrearCuentaFOperationCompleted(object arg) {
            if ((this.crearCuentaFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearCuentaFCompleted(this, new crearCuentaFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/crearCuentaF2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("crearCuentaFResult")]
        public int crearCuentaF2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nombreEmpresa, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string razonSocial, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string correoElectronico, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string apiKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string idDistribuidor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("crearCuentaF2", new object[] {
                        nombreEmpresa,
                        rfc,
                        razonSocial,
                        correoElectronico,
                        apiKey,
                        idDistribuidor,
                        idCuenta,
                        passwordCuenta,
                        mensajeError});
            apiKey = ((string)(results[1]));
            idDistribuidor = ((string)(results[2]));
            idCuenta = ((string)(results[3]));
            passwordCuenta = ((string)(results[4]));
            mensajeError = ((string)(results[5]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void crearCuentaF2Async(string nombreEmpresa, string rfc, string razonSocial, string correoElectronico, string apiKey, string idDistribuidor, string idCuenta, string passwordCuenta, string mensajeError) {
            this.crearCuentaF2Async(nombreEmpresa, rfc, razonSocial, correoElectronico, apiKey, idDistribuidor, idCuenta, passwordCuenta, mensajeError, null);
        }
        
        /// <remarks/>
        public void crearCuentaF2Async(string nombreEmpresa, string rfc, string razonSocial, string correoElectronico, string apiKey, string idDistribuidor, string idCuenta, string passwordCuenta, string mensajeError, object userState) {
            if ((this.crearCuentaF2OperationCompleted == null)) {
                this.crearCuentaF2OperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearCuentaF2OperationCompleted);
            }
            this.InvokeAsync("crearCuentaF2", new object[] {
                        nombreEmpresa,
                        rfc,
                        razonSocial,
                        correoElectronico,
                        apiKey,
                        idDistribuidor,
                        idCuenta,
                        passwordCuenta,
                        mensajeError}, this.crearCuentaF2OperationCompleted, userState);
        }
        
        private void OncrearCuentaF2OperationCompleted(object arg) {
            if ((this.crearCuentaF2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearCuentaF2Completed(this, new crearCuentaF2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/agregarContribuyenteF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int agregarContribuyenteF([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string razonSocial, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("agregarContribuyenteF", new object[] {
                        idCuenta,
                        passwordCuenta,
                        rfc,
                        razonSocial,
                        mensajeError});
            mensajeError = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void agregarContribuyenteFAsync(string idCuenta, string passwordCuenta, string rfc, string razonSocial, string mensajeError) {
            this.agregarContribuyenteFAsync(idCuenta, passwordCuenta, rfc, razonSocial, mensajeError, null);
        }
        
        /// <remarks/>
        public void agregarContribuyenteFAsync(string idCuenta, string passwordCuenta, string rfc, string razonSocial, string mensajeError, object userState) {
            if ((this.agregarContribuyenteFOperationCompleted == null)) {
                this.agregarContribuyenteFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnagregarContribuyenteFOperationCompleted);
            }
            this.InvokeAsync("agregarContribuyenteF", new object[] {
                        idCuenta,
                        passwordCuenta,
                        rfc,
                        razonSocial,
                        mensajeError}, this.agregarContribuyenteFOperationCompleted, userState);
        }
        
        private void OnagregarContribuyenteFOperationCompleted(object arg) {
            if ((this.agregarContribuyenteFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.agregarContribuyenteFCompleted(this, new agregarContribuyenteFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/quitarContribuyenteF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int quitarContribuyenteF([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("quitarContribuyenteF", new object[] {
                        idCuenta,
                        passwordCuenta,
                        rfc,
                        mensajeError});
            mensajeError = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void quitarContribuyenteFAsync(string idCuenta, string passwordCuenta, string rfc, string mensajeError) {
            this.quitarContribuyenteFAsync(idCuenta, passwordCuenta, rfc, mensajeError, null);
        }
        
        /// <remarks/>
        public void quitarContribuyenteFAsync(string idCuenta, string passwordCuenta, string rfc, string mensajeError, object userState) {
            if ((this.quitarContribuyenteFOperationCompleted == null)) {
                this.quitarContribuyenteFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnquitarContribuyenteFOperationCompleted);
            }
            this.InvokeAsync("quitarContribuyenteF", new object[] {
                        idCuenta,
                        passwordCuenta,
                        rfc,
                        mensajeError}, this.quitarContribuyenteFOperationCompleted, userState);
        }
        
        private void OnquitarContribuyenteFOperationCompleted(object arg) {
            if ((this.quitarContribuyenteFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.quitarContribuyenteFCompleted(this, new quitarContribuyenteFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/obtenerXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int obtenerXML([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfc, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string XMLDestino, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("obtenerXML", new object[] {
                        idCuenta,
                        passwordCuenta,
                        uuid,
                        rfc,
                        XMLDestino,
                        mensajeError});
            XMLDestino = ((string)(results[1]));
            mensajeError = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerXMLAsync(string idCuenta, string passwordCuenta, string uuid, string rfc, string XMLDestino, string mensajeError) {
            this.obtenerXMLAsync(idCuenta, passwordCuenta, uuid, rfc, XMLDestino, mensajeError, null);
        }
        
        /// <remarks/>
        public void obtenerXMLAsync(string idCuenta, string passwordCuenta, string uuid, string rfc, string XMLDestino, string mensajeError, object userState) {
            if ((this.obtenerXMLOperationCompleted == null)) {
                this.obtenerXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerXMLOperationCompleted);
            }
            this.InvokeAsync("obtenerXML", new object[] {
                        idCuenta,
                        passwordCuenta,
                        uuid,
                        rfc,
                        XMLDestino,
                        mensajeError}, this.obtenerXMLOperationCompleted, userState);
        }
        
        private void OnobtenerXMLOperationCompleted(object arg) {
            if ((this.obtenerXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerXMLCompleted(this, new obtenerXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/obtenerEstatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int obtenerEstatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string xmlRespuesta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string total, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("obtenerEstatus", new object[] {
                        idCuenta,
                        passwordCuenta,
                        uuid,
                        rfcEmisor,
                        rfcReceptor,
                        xmlRespuesta,
                        total,
                        mensajeError});
            xmlRespuesta = ((string)(results[1]));
            mensajeError = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerEstatusAsync(string idCuenta, string passwordCuenta, string uuid, string rfcEmisor, string rfcReceptor, string xmlRespuesta, string total, string mensajeError) {
            this.obtenerEstatusAsync(idCuenta, passwordCuenta, uuid, rfcEmisor, rfcReceptor, xmlRespuesta, total, mensajeError, null);
        }
        
        /// <remarks/>
        public void obtenerEstatusAsync(string idCuenta, string passwordCuenta, string uuid, string rfcEmisor, string rfcReceptor, string xmlRespuesta, string total, string mensajeError, object userState) {
            if ((this.obtenerEstatusOperationCompleted == null)) {
                this.obtenerEstatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerEstatusOperationCompleted);
            }
            this.InvokeAsync("obtenerEstatus", new object[] {
                        idCuenta,
                        passwordCuenta,
                        uuid,
                        rfcEmisor,
                        rfcReceptor,
                        xmlRespuesta,
                        total,
                        mensajeError}, this.obtenerEstatusOperationCompleted, userState);
        }
        
        private void OnobtenerEstatusOperationCompleted(object arg) {
            if ((this.obtenerEstatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerEstatusCompleted(this, new obtenerEstatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/obtenerRelacionados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int obtenerRelacionados([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcContribuyente, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string UUID, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] cer, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] key, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string xmlRespuesta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("obtenerRelacionados", new object[] {
                        idCuenta,
                        passwordCuenta,
                        rfcReceptor,
                        rfcContribuyente,
                        UUID,
                        cer,
                        key,
                        xmlRespuesta,
                        mensajeError});
            xmlRespuesta = ((string)(results[1]));
            mensajeError = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerRelacionadosAsync(string idCuenta, string passwordCuenta, string rfcReceptor, string rfcContribuyente, string UUID, byte[] cer, byte[] key, string xmlRespuesta, string mensajeError) {
            this.obtenerRelacionadosAsync(idCuenta, passwordCuenta, rfcReceptor, rfcContribuyente, UUID, cer, key, xmlRespuesta, mensajeError, null);
        }
        
        /// <remarks/>
        public void obtenerRelacionadosAsync(string idCuenta, string passwordCuenta, string rfcReceptor, string rfcContribuyente, string UUID, byte[] cer, byte[] key, string xmlRespuesta, string mensajeError, object userState) {
            if ((this.obtenerRelacionadosOperationCompleted == null)) {
                this.obtenerRelacionadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerRelacionadosOperationCompleted);
            }
            this.InvokeAsync("obtenerRelacionados", new object[] {
                        idCuenta,
                        passwordCuenta,
                        rfcReceptor,
                        rfcContribuyente,
                        UUID,
                        cer,
                        key,
                        xmlRespuesta,
                        mensajeError}, this.obtenerRelacionadosOperationCompleted, userState);
        }
        
        private void OnobtenerRelacionadosOperationCompleted(object arg) {
            if ((this.obtenerRelacionadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerRelacionadosCompleted(this, new obtenerRelacionadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/uuidsCancelacionPendientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int uuidsCancelacionPendientes([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcConsultar, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcContribuyente, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string xmlRespuesta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("uuidsCancelacionPendientes", new object[] {
                        idCuenta,
                        passwordCuenta,
                        rfcConsultar,
                        rfcContribuyente,
                        xmlRespuesta,
                        mensajeError});
            xmlRespuesta = ((string)(results[1]));
            mensajeError = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void uuidsCancelacionPendientesAsync(string idCuenta, string passwordCuenta, string rfcConsultar, string rfcContribuyente, string xmlRespuesta, string mensajeError) {
            this.uuidsCancelacionPendientesAsync(idCuenta, passwordCuenta, rfcConsultar, rfcContribuyente, xmlRespuesta, mensajeError, null);
        }
        
        /// <remarks/>
        public void uuidsCancelacionPendientesAsync(string idCuenta, string passwordCuenta, string rfcConsultar, string rfcContribuyente, string xmlRespuesta, string mensajeError, object userState) {
            if ((this.uuidsCancelacionPendientesOperationCompleted == null)) {
                this.uuidsCancelacionPendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuuidsCancelacionPendientesOperationCompleted);
            }
            this.InvokeAsync("uuidsCancelacionPendientes", new object[] {
                        idCuenta,
                        passwordCuenta,
                        rfcConsultar,
                        rfcContribuyente,
                        xmlRespuesta,
                        mensajeError}, this.uuidsCancelacionPendientesOperationCompleted, userState);
        }
        
        private void OnuuidsCancelacionPendientesOperationCompleted(object arg) {
            if ((this.uuidsCancelacionPendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uuidsCancelacionPendientesCompleted(this, new uuidsCancelacionPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/aceptarRechazarCancelacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int aceptarRechazarCancelacion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idCuenta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passwordCuenta, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] cer, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] key, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string rfcContribuyente, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string uuid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string respuesta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string xmlRespuesta, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string mensajeError) {
            object[] results = this.Invoke("aceptarRechazarCancelacion", new object[] {
                        idCuenta,
                        passwordCuenta,
                        cer,
                        key,
                        rfcReceptor,
                        rfcContribuyente,
                        uuid,
                        respuesta,
                        xmlRespuesta,
                        mensajeError});
            xmlRespuesta = ((string)(results[1]));
            mensajeError = ((string)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void aceptarRechazarCancelacionAsync(string idCuenta, string passwordCuenta, byte[] cer, byte[] key, string rfcReceptor, string rfcContribuyente, string uuid, string respuesta, string xmlRespuesta, string mensajeError) {
            this.aceptarRechazarCancelacionAsync(idCuenta, passwordCuenta, cer, key, rfcReceptor, rfcContribuyente, uuid, respuesta, xmlRespuesta, mensajeError, null);
        }
        
        /// <remarks/>
        public void aceptarRechazarCancelacionAsync(string idCuenta, string passwordCuenta, byte[] cer, byte[] key, string rfcReceptor, string rfcContribuyente, string uuid, string respuesta, string xmlRespuesta, string mensajeError, object userState) {
            if ((this.aceptarRechazarCancelacionOperationCompleted == null)) {
                this.aceptarRechazarCancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaceptarRechazarCancelacionOperationCompleted);
            }
            this.InvokeAsync("aceptarRechazarCancelacion", new object[] {
                        idCuenta,
                        passwordCuenta,
                        cer,
                        key,
                        rfcReceptor,
                        rfcContribuyente,
                        uuid,
                        respuesta,
                        xmlRespuesta,
                        mensajeError}, this.aceptarRechazarCancelacionOperationCompleted, userState);
        }
        
        private void OnaceptarRechazarCancelacionOperationCompleted(object arg) {
            if ((this.aceptarRechazarCancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aceptarRechazarCancelacionCompleted(this, new aceptarRechazarCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void timbrarXMLCompletedEventHandler(object sender, timbrarXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbrarXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbrarXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string XMLDestino {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cancelarXMLCompletedEventHandler(object sender, cancelarXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string acuseRecibo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cancelarXMLExternoCompletedEventHandler(object sender, cancelarXMLExternoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarXMLExternoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarXMLExternoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string acuseRecibo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void verificarVigenciaCompletedEventHandler(object sender, verificarVigenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificarVigenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificarVigenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string detallesLicencia {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void crearCuentaFCompletedEventHandler(object sender, crearCuentaFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearCuentaFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearCuentaFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string idCuenta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string passwordCuenta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void crearCuentaF2CompletedEventHandler(object sender, crearCuentaF2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearCuentaF2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearCuentaF2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string apiKey {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string idDistribuidor {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string idCuenta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string passwordCuenta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void agregarContribuyenteFCompletedEventHandler(object sender, agregarContribuyenteFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class agregarContribuyenteFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal agregarContribuyenteFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void quitarContribuyenteFCompletedEventHandler(object sender, quitarContribuyenteFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class quitarContribuyenteFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal quitarContribuyenteFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerXMLCompletedEventHandler(object sender, obtenerXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string XMLDestino {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerEstatusCompletedEventHandler(object sender, obtenerEstatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerEstatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerEstatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string xmlRespuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void obtenerRelacionadosCompletedEventHandler(object sender, obtenerRelacionadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerRelacionadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerRelacionadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string xmlRespuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void uuidsCancelacionPendientesCompletedEventHandler(object sender, uuidsCancelacionPendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uuidsCancelacionPendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uuidsCancelacionPendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string xmlRespuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void aceptarRechazarCancelacionCompletedEventHandler(object sender, aceptarRechazarCancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aceptarRechazarCancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aceptarRechazarCancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string xmlRespuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591