If Exists ( Select Name From Sysobjects (NoLock) Where Name = 'CierreInventario_Tablas_Limpiar' and xType = 'U' )
	Drop Table CierreInventario_Tablas_Limpiar 
Go--#SQL 

Create Table CierreInventario_Tablas_Limpiar 
(
	Tabla varchar(100) Not Null, 
	TieneEmpresa bit Not Null Default 'true', 
	Keyx int identity(1,1) 
) 
Go--#SQL 


-- Se insertan las tablas 


 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CatMedicos_Historico', 0 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CatBeneficiarios_Historico', 0 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Ventas_TiempoAire', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Ventas_ALMJ_PedidosRC_Surtido', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ALMJ_Concentrado_PedidosRC_Pedidos', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ALMJ_Concentrado_PedidosRC_Claves', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ALMJ_Concentrado_PedidosRC', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ALMJ_Pedidos_RC_Det', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ALMJ_Pedidos_RC', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Pedidos_Cedis_Det_Surtido_Distribucion_Reproceso', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Pedidos_Cedis_Det_Surtido_Distribucion', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Pedidos_Cedis_Enc_Surtido_Atenciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Pedidos_Cedis_Enc_Surtido', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Pedidos_Cedis_Det_Pedido_Distribuidor', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Pedidos_Cedis_Det_Surtido', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Pedidos_Cedis_Det', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Pedidos_Cedis_Enc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosDistDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosDistDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosDistEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosEnvioDet_Lotes_Registrar', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosEnvioDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosEnvioDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosEnvioEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosDet_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PedidosEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PreSalidasPedidosDet_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PreSalidasPedidosDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'PreSalidasPedidosEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'DevolucionTransferenciasDet_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'DevolucionTransferenciasDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'DevolucionTransferenciasDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'DevolucionTransferenciasEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'DevolucionesDet_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'DevolucionesDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'DevolucionesDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'DevolucionesEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'TraspasosDet_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'TraspasosDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'TraspasosDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'TraspasosEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'TransferenciasDet_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'TransferenciasDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'TransferenciasDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'TransferenciasEnc', 1 ) 
 
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'MovtosInv_Adt_Devoluciones', 1 )      
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Adt_OrdenesDeComprasEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Adt_ComprasEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Adt_FarmaciaProductos_CodigoEAN_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Adt_VentasInformacionAdicional', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Adt_VentasEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ComprasDet_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ComprasDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ComprasDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ComprasEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'RemisionesDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'RemisionesDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'RemisionesEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Vales_Cancelacion', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ValesDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ValesDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'ValesEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Vales_Emision_InformacionAdicional', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Vales_EmisionDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Vales_EmisionEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'VentasEstadisticaClavesDispensadas', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'VentasInformacionAdicional', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'VentasEstDispensacion', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'VentasDet_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'VentasDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'VentasDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'VentasEnc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CambiosProv_Det_CodigosEAN_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CambiosProv_Det_CodigosEAN', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CambiosProv_Enc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'AjustesInv_Det_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'AjustesInv_Det_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'AjustesInv_Det', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'AjustesInv_Enc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'EntradasDet_Consignacion_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'EntradasDet_Consignacion_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'EntradasDet_Consignacion', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'EntradasEnc_Consignacion', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'MovtosInv_Det_CodigosEAN_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'MovtosInv_Det_CodigosEAN_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'MovtosInv_Det_CodigosEAN', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'MovtosInv_ADT', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'MovtosInv_Enc', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'FarmaciaProductos_CodigoEAN_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'OrdenesDeComprasDet_Lotes_Ubicaciones', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'OrdenesDeComprasDet_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'OrdenesDeComprasDet', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'OrdenesDeComprasEnc', 1 )   

 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'FarmaciaProductos_CodigoEAN_Lotes__Historico', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'FarmaciaProductos_CodigoEAN_Lotes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'FarmaciaProductos_CodigoEAN', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'FarmaciaProductos', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CatPasillos_Estantes_Entrepaños', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CatPasillos_Estantes', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CatPasillos', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Ctl_CierresPeriodosDetalles', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'Ctl_CierresDePeriodos', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CtlCortesDiarios', 1 )   
 Insert Into CierreInventario_Tablas_Limpiar (  Tabla, TieneEmpresa )  Values ( 'CtlCortesParciales', 1 )   

 Go--#SQL 

