-----------------------------------------------------------------------------------------------------------------------------------------------------------------  
If Not Exists ( Select So.* From sysobjects So (NoLock) Where So.Name = 'CFG_Almacenes_PermisosEspeciales' and xType = 'U' )  
Begin 	

	Create Table CFG_Almacenes_PermisosEspeciales  
	( 
		IdEstado varchar(2) Not Null, 
		IdFarmacia varchar(4) Not Null,
		Status varchar(1) Not Null Default '', 
		MD5 varchar(500) Not Null Default '',
		FechaVigencia Varchar(10) Not Null Default ''
	) 

	Alter Table CFG_Almacenes_PermisosEspeciales Add Constraint PK_CFG_Almacenes_PermisosEspeciales 
		Primary Key ( IdEstado, IdFarmacia ) 

	Alter Table CFG_Almacenes_PermisosEspeciales Add Constraint FK_CFG_Almacenes_PermisosEspeciales___CatFarmacias 
		Foreign Key ( IdEstado, IdFarmacia ) References CatFarmacias ( IdEstado, IdFarmacia ) 

End 
Go--#SQL


If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '09' and IdFarmacia = '0002' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '09', '0002', 'A', '—QW“j„ƒWY™SbUUKscsolutionsPYœPPPRœaœRPQYMPXMSQKRSPƒx…‘f™”Tqz–', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = '—QW“j„ƒWY™SbUUKscsolutionsPYœPPPRœaœRPQYMPXMSQKRSPƒx…‘f™”Tqz–', FechaVigencia = '2019-08-31' Where IdEstado = '09' and IdFarmacia = '0002'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '09' and IdFarmacia = '0023' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '09', '0023', 'A', 'Xsfic‚jp—š†v™b˜PŒscsolutionsPYœPPRSœaœRPQYMPXMSQˆ”hewƒlm˜sPW—T—PS', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'Xsfic‚jp—š†v™b˜PŒscsolutionsPYœPPRSœaœRPQYMPXMSQˆ”hewƒlm˜sPW—T—PS', FechaVigencia = '2019-08-31' Where IdEstado = '09' and IdFarmacia = '0023'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '09' and IdFarmacia = '0101' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '09', '0101', 'A', 'pwbYY™PfdKiˆ…Q…scsolutionsPYœPQPQœaœRPQYMPXMSQ—srvYfˆv‡nbt„Š', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'pwbYY™PfdKiˆ…Q…scsolutionsPYœPQPQœaœRPQYMPXMSQ—srvYfˆv‡nbt„Š', FechaVigencia = '2019-08-31' Where IdEstado = '09' and IdFarmacia = '0101'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '11' and IdFarmacia = '1005' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '11', '1005', 'A', 'y‹SYexš“ŒKprŒfxscsolutionsQQœQPPUœaœRPQYMPXMSQ‹–™Tct–peqmif‡‘”—', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'y‹SYexš“ŒKprŒfxscsolutionsQQœQPPUœaœRPQYMPXMSQ‹–™Tct–peqmif‡‘”—', FechaVigencia = '2019-08-31' Where IdEstado = '11' and IdFarmacia = '1005'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '11' and IdFarmacia = '1601' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '11', '1601', 'A', 'qU‹‰h†‘Œm†™–duh•‚scsolutionsQQœQVPQœaœRPQYMPXMSQa†•ed…ƒs—’uŠ’™y…', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'qU‹‰h†‘Œm†™–duh•‚scsolutionsQQœQVPQœaœRPQYMPXMSQa†•ed…ƒs—’uŠ’™y…', FechaVigencia = '2019-08-31' Where IdEstado = '11' and IdFarmacia = '1601'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '11' and IdFarmacia = '1602' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '11', '1602', 'A', '‚bkS‰h”xqe‡•Œqw™‡scsolutionsQQœQVPRœaœRPQYMPXMSQi•ru‰d”S˜•rn–““v‰', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = '‚bkS‰h”xqe‡•Œqw™‡scsolutionsQQœQVPRœaœRPQYMPXMSQi•ru‰d”S˜•rn–““v‰', FechaVigencia = '2019-08-31' Where IdEstado = '11' and IdFarmacia = '1602'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '13' and IdFarmacia = '0003' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '13', '0003', 'A', 'Kvam–‰VvbaQe“nY…scsolutionsQSœPPPSœaœRPQYMPXMSQxRS”™‰su•”gRyˆ„', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'Kvam–‰VvbaQe“nY…scsolutionsQSœPPPSœaœRPQYMPXMSQxRS”™‰su•”gRyˆ„', FechaVigencia = '2019-08-31' Where IdEstado = '13' and IdFarmacia = '0003'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '13' and IdFarmacia = '0004' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '13', '0004', 'A', 'sOeiqƒzoj†mWpV—scsolutionsQSœPPPTœaœRPQYMPXMSQ†’qKczKgtš‚Rms‹xv', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'sOeiqƒzoj†mWpV—scsolutionsQSœPPPTœaœRPQYMPXMSQ†’qKczKgtš‚Rms‹xv', FechaVigencia = '2019-08-31' Where IdEstado = '13' and IdFarmacia = '0004'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '14' and IdFarmacia = '0002' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '14', '0002', 'A', 'edŒ‰ŠTxjˆ–Œ–™scsolutionsQTœPPPRœaœRPQYMPXMSQh•‚KO„Š“WenzYbšQS', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'edŒ‰ŠTxjˆ–Œ–™scsolutionsQTœPPPRœaœRPQYMPXMSQh•‚KO„Š“WenzYbšQS', FechaVigencia = '2019-08-31' Where IdEstado = '14' and IdFarmacia = '0002'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '14' and IdFarmacia = '0003' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '14', '0003', 'A', 'yf…ƒYr„•udg”t…yRscsolutionsQTœPPPSœaœRPQYMPXMSQ–iSnmlfSo„ThwQ', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'yf…ƒYr„•udg”t…yRscsolutionsQTœPPPSœaœRPQYMPXMSQ–iSnmlfSo„ThwQ', FechaVigencia = '2019-08-31' Where IdEstado = '14' and IdFarmacia = '0003'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '14' and IdFarmacia = '0005' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '14', '0005', 'A', 'ˆWšlh„fvˆ‚bt‚ŒrušscsolutionsQTœPPPUœaœRPQYMPXMSQQ—ˆšgjukaouX•…', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'ˆWšlh„fvˆ‚bt‚ŒrušscsolutionsQTœPPPUœaœRPQYMPXMSQQ—ˆšgjukaouX•…', FechaVigencia = '2019-08-31' Where IdEstado = '14' and IdFarmacia = '0005'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '21' and IdFarmacia = '1000' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '21', '1000', 'A', '‰V‘q—ˆyjjU“XnˆscsolutionsRQœQPPPœaœRPQYMPXMSQ‘uYstSuT†•m˜SkmzŒ', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = '‰V‘q—ˆyjjU“XnˆscsolutionsRQœQPPPœaœRPQYMPXMSQ‘uYstSuT†•m˜SkmzŒ', FechaVigencia = '2019-08-31' Where IdEstado = '21' and IdFarmacia = '1000'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '21' and IdFarmacia = '3182' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '21', '3182', 'A', 'aSkK“pswmšbP’oz—wscsolutionsRQœSQXRœaœRPQYMPXMSQtnqR‹‡ƒš‰„syYw–', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'aSkK“pswmšbP’oz—wscsolutionsRQœSQXRœaœRPQYMPXMSQtnqR‹‡ƒš‰„syYw–', FechaVigencia = '2019-08-31' Where IdEstado = '21' and IdFarmacia = '3182'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '21' and IdFarmacia = '3414' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '21', '3414', 'A', 'irŒŠˆ™tQŒkbVˆwifscsolutionsRQœSTQTœaœRPQYMPXMSQ“nmOfŒiiK‡gjR™OŠ', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = 'irŒŠˆ™tQŒkbVˆwifscsolutionsRQœSTQTœaœRPQYMPXMSQ“nmOfŒiiK‡gjR™OŠ', FechaVigencia = '2019-08-31' Where IdEstado = '21' and IdFarmacia = '3414'  
If Not Exists ( Select * From CFG_Almacenes_PermisosEspeciales Where IdEstado = '28' and IdFarmacia = '0103' )  Insert Into CFG_Almacenes_PermisosEspeciales (  IdEstado, IdFarmacia, Status, MD5, FechaVigencia )  Values ( '28', '0103', 'A', '‹„qTtŒvjntst•qƒ‡scsolutionsRXœPQPSœaœRPQYMPXMSQUz„Œe’qt•uy‰eW’˜O', '2019-08-31' )  Else Update CFG_Almacenes_PermisosEspeciales Set Status = 'A', MD5 = '‹„qTtŒvjntst•qƒ‡scsolutionsRXœPQPSœaœRPQYMPXMSQUz„Œe’qt•uy‰eW’˜O', FechaVigencia = '2019-08-31' Where IdEstado = '28' and IdFarmacia = '0103'  
Go--#SQL

