
-----------------------------------------------------------------------------------------------------------------------------------  
If Exists ( Select Name From Sysobjects (NoLock) Where Name = 'FACT_Fuentes_De_Financiamiento_Detalles_Documentos'  and xType = 'U' ) 
   Drop Table FACT_Fuentes_De_Financiamiento_Detalles_Documentos
Go--#SQL   


-----------------------------------------------------------------------------------------------------------------------------------  
If Exists ( Select Name From Sysobjects (NoLock) Where Name = 'FACT_Fuentes_De_Financiamiento_Detalles_Documentos'  and xType = 'U' ) 
   Drop Table FACT_Fuentes_De_Financiamiento_Detalles_Documentos   
Go--#SQL   

Create Table FACT_Fuentes_De_Financiamiento_Detalles_Documentos 
(
	IdFuenteFinanciamiento varchar(4) Not Null, 
	IdFinanciamiento varchar(4) Not Null, 
	IdDocumento varchar(4) Not Null,  
	NombreDocumento varchar(200) Not Null Default '', 

	IdFuenteFinanciamiento_Relacionado varchar(4) Not Null Default '', 
	IdFinanciamiento_Relacionado varchar(4) Not Null Default '', 
	IdDocumento_Relacionado varchar(4) Not Null Default '',  
	EsRelacionado bit Not Null default 'false', 

	OrigenDeInsumo int Not Null Default 0,		-- 0 ==> General | 1 ==> Venta | 2 ==> Consigna 
	TipoDeDocumento int Not Null Default 0,		-- 1 ==> Producto | 2 ==> Servicio 
	TipoDeInsumo int Not Null Default 0,		-- 0 ==> General | 1 ==> Medicamento | 2 ==> Material de curacion 
	ValorNominal numeric(14,4) Not Null Default 0,   
	ImporteAplicado numeric(14,4) Not Null Default 0, 
	ImporteAplicado_Aux numeric(14,4) Not Null Default 0, 
	ImporteRestante numeric(14,4) Not Null Default 0, 

	AplicaFarmacia bit Not Null default 'false', 
	AplicaAlmacen bit Not Null default 'false', 
	EsProgramaEspecial bit Not Null default 'false', 
	TipoDeBeneficiario int Not Null Default 0,		-- 0 ==> Todos | 1 ==> General <Solo farmacia> | 2 ==> Hospitales <Solo almacén> | 3 ==> Jurisdicciones <Solo almacén> 

	Status varchar(1) Not Null Default 'A', 
	Actualizado smallint Not Null Default 0 

)
Go--#SQL 
 
Alter Table FACT_Fuentes_De_Financiamiento_Detalles_Documentos 
	Add Constraint PK_FACT_Fuentes_De_Financiamiento_Detalles_Documentos Primary Key (  IdFuenteFinanciamiento, IdFinanciamiento , IdDocumento ) 
Go--#SQL 

Alter Table FACT_Fuentes_De_Financiamiento_Detalles_Documentos 
Add Constraint FACT_Fuentes_De_Financiamiento_Detalles_Documentos___FACT_Fuentes_De_Financiamiento_Detalles   
	Foreign Key ( IdFuenteFinanciamiento, IdFinanciamiento ) 
	References FACT_Fuentes_De_Financiamiento_Detalles ( IdFuenteFinanciamiento, IdFinanciamiento ) 
Go--#SQL 



----------------------------------------------------------------- SOLO TAMAULIPAS 

If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0001' and IdDocumento = '0001' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0001', '0001', 'OC-4550000415', '', '', '', 0, 1, 1, 2, 96000000.0000, 0.0000, 0.0000, 96000000.0000, 0, 1, 0, 'A', 0, 3 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000415', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 96000000.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 96000000.0000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 3 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0001' and IdDocumento = '0001'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0001' and IdDocumento = '0002' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0001', '0002', 'OC-4550000416', '', '', '', 0, 1, 1, 2, 144000000.0000, 17610719.8600, 13167225.3600, 130832774.6400, 1, 0, 0, 'A', 0, 2 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000416', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 144000000.0000, ImporteAplicado = 17610719.8600, ImporteAplicado_Aux = 13167225.3600, ImporteRestante = 130832774.6400, AplicaFarmacia = 1, AplicaAlmacen = 0, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 2 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0001' and IdDocumento = '0002'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0001' and IdDocumento = '0003' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0001', '0003', 'OC-4550000419', '', '', '', 0, 1, 1, 1, 9252267.7200, 27727.3000, 27727.3000, 9224540.4200, 0, 1, 0, 'A', 0, 3 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000419', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 1, ValorNominal = 9252267.7200, ImporteAplicado = 27727.3000, ImporteAplicado_Aux = 27727.3000, ImporteRestante = 9224540.4200, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 3 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0001' and IdDocumento = '0003'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0001' and IdDocumento = '0004' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0001', '0004', 'OC-4550000420', '', '', '', 0, 1, 1, 1, 13878401.5800, 0.0000, 0.0000, 13878401.5800, 0, 1, 0, 'A', 0, 2 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000420', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 1, ValorNominal = 13878401.5800, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 13878401.5800, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 2 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0001' and IdDocumento = '0004'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0001' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0001', 'OC-4550000417', '', '', '', 0, 1, 1, 2, 21252267.7200, 0.0000, 0.0000, 21252267.7200, 0, 1, 0, 'A', 0, 3 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000417', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 21252267.7200, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 21252267.7200, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 3 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0001'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0002' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0002', 'OC-4550000418', '', '', '', 0, 1, 1, 2, 31878401.5800, 3476343.3700, 3047859.7200, 28830541.8600, 1, 0, 0, 'A', 0, 2 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000418', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 31878401.5800, ImporteAplicado = 3476343.3700, ImporteAplicado_Aux = 3047859.7200, ImporteRestante = 28830541.8600, AplicaFarmacia = 1, AplicaAlmacen = 0, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 2 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0002'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0003' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0003', 'OC-4550000421', '', '', '', 0, 1, 1, 1, 30747732.2800, 0.0000, 0.0000, 30747732.2800, 0, 1, 0, 'A', 0, 3 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000421', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 1, ValorNominal = 30747732.2800, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 30747732.2800, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 3 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0003'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0004' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0004', 'OC-4550000422', '', '', '', 0, 1, 1, 1, 46121598.4200, 3312372.9800, 3312372.9800, 42809225.4400, 0, 1, 0, 'A', 0, 2 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000422', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 1, ValorNominal = 46121598.4200, ImporteAplicado = 3312372.9800, ImporteAplicado_Aux = 3312372.9800, ImporteRestante = 42809225.4400, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 2 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0004'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0005' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0005', 'OC-4550000423', '', '', '', 0, 1, 1, 2, 1017588.4000, 0.0000, 0.0000, 1017588.4000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000423', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 1017588.4000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1017588.4000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0005'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0006' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0006', 'OC-4550000424', '', '', '', 0, 1, 1, 2, 602870.4000, 0.0000, 0.0000, 602870.4000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000424', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 602870.4000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 602870.4000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0006'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0007' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0007', 'OC-4550000425', '', '', '', 0, 1, 1, 2, 408000.0000, 0.0000, 0.0000, 408000.0000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000425', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 408000.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 408000.0000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0007'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0008' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0008', 'OC-4550000426', '', '', '', 0, 1, 1, 2, 1418088.4000, 1418069.4300, 1418069.4300, 18.9700, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000426', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 1418088.4000, ImporteAplicado = 1418069.4300, ImporteAplicado_Aux = 1418069.4300, ImporteRestante = 18.9700, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0008'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0009' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0009', 'OC-4550000427', '', '', '', 0, 1, 1, 2, 1710193.2000, 0.0000, 0.0000, 1710193.2000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000427', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 1710193.2000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1710193.2000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0009'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0010' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0010', 'OC-4550000428', '', '', '', 0, 1, 1, 2, 2376084.0000, 0.0000, 0.0000, 2376084.0000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000428', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 2376084.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 2376084.0000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0010'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0011' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0011', 'OC-4550000429', '', '', '', 0, 1, 1, 2, 1380761.2000, 0.0000, 0.0000, 1380761.2000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000429', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 1380761.2000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1380761.2000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0011'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0012' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0012', 'OC-4550000430', '', '', '', 0, 1, 1, 2, 1245604.8000, 0.0000, 0.0000, 1245604.8000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000430', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 1245604.8000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1245604.8000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0012'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0013' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0013', 'OC-4550000431', '', '', '', 0, 1, 1, 2, 1051767.6000, 0.0000, 0.0000, 1051767.6000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000431', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 1051767.6000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1051767.6000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0013'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0014' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0014', 'OC-4550000432', '', '', '', 0, 1, 1, 2, 816774.4000, 0.0000, 0.0000, 816774.4000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000432', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 816774.4000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 816774.4000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0014'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0015' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0015', 'OC-4550000433', '', '', '', 0, 1, 1, 2, 2126382.6000, 0.0000, 0.0000, 2126382.6000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000433', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 2126382.6000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 2126382.6000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0015'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0016' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0016', 'OC-4550000434', '', '', '', 0, 1, 1, 2, 904305.6000, 0.0000, 0.0000, 904305.6000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000434', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 904305.6000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 904305.6000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0016'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0017' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0017', 'OC-4550000435', '', '', '', 0, 1, 1, 2, 612000.0000, 0.0000, 0.0000, 612000.0000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000435', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 612000.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 612000.0000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0017'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0018' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0018', 'OC-4550000436', '', '', '', 0, 1, 1, 2, 2127132.6000, 2127130.7300, 2127130.7300, 1.8700, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000436', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 2127132.6000, ImporteAplicado = 2127130.7300, ImporteAplicado_Aux = 2127130.7300, ImporteRestante = 1.8700, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0018'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0019' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0019', 'OC-4550000437', '', '', '', 0, 1, 1, 2, 2565289.8000, 0.0000, 0.0000, 2565289.8000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000437', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 2565289.8000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 2565289.8000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0019'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0020' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0020', 'OC-4550000438', '', '', '', 0, 1, 1, 2, 3564126.0000, 0.0000, 0.0000, 3564126.0000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000438', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 3564126.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 3564126.0000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0020'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0021' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0021', 'OC-4550000439', '', '', '', 0, 1, 1, 2, 2071141.8000, 0.0000, 0.0000, 2071141.8000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000439', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 2071141.8000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 2071141.8000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0021'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0022' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0022', 'OC-4550000440', '', '', '', 0, 1, 1, 2, 1868407.2000, 0.0000, 0.0000, 1868407.2000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000440', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 1868407.2000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1868407.2000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0022'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0023' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0023', 'OC-4550000441', '', '', '', 0, 1, 1, 2, 1577651.4000, 0.0000, 0.0000, 1577651.4000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000441', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 1577651.4000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1577651.4000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0023'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0024' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0024', 'OC-4550000442', '', '', '', 0, 1, 1, 2, 1225161.6000, 0.0000, 0.0000, 1225161.6000, 0, 1, 1, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000442', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 1, TipoDeInsumo = 2, ValorNominal = 1225161.6000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1225161.6000, AplicaFarmacia = 0, AplicaAlmacen = 1, EsProgramaEspecial = 1, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0024'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0025' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0025', 'OC-4550000443', '', '', '', 0, 1, 2, 0, 2835176.8000, 2835173.9800, 2835173.9800, 2.8200, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000443', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 2835176.8000, ImporteAplicado = 2835173.9800, ImporteAplicado_Aux = 2835173.9800, ImporteRestante = 2.8200, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0025'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0026' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0026', 'OC-4550000444', '', '', '', 0, 1, 2, 0, 1550276.2300, 1550268.0800, 1546955.1200, 3321.1100, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000444', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 1550276.2300, ImporteAplicado = 1550268.0800, ImporteAplicado_Aux = 1546955.1200, ImporteRestante = 3321.1100, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0026'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0027' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0027', 'OC-4550000445', '', '', '', 0, 1, 2, 0, 816000.0000, 815993.8800, 815993.8800, 6.1200, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000445', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 816000.0000, ImporteAplicado = 815993.8800, ImporteAplicado_Aux = 815993.8800, ImporteRestante = 6.1200, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0027'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0028' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0028', 'OC-4550000446', '', '', '', 0, 1, 2, 0, 2836176.8000, 2836169.8400, 2836169.8400, 6.9600, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000446', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 2836176.8000, ImporteAplicado = 2836169.8400, ImporteAplicado_Aux = 2836169.8400, ImporteRestante = 6.9600, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0028'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0029' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0029', 'OC-4550000447', '', '', '', 0, 1, 2, 0, 4220386.4000, 4220385.6600, 4220385.6600, 0.7400, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000447', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 4220386.4000, ImporteAplicado = 4220385.6600, ImporteAplicado_Aux = 4220385.6600, ImporteRestante = 0.7400, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0029'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0030' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0030', 'OC-4550000448', '', '', '', 0, 1, 2, 0, 2761522.3000, 2761519.7800, 2761519.7800, 2.5200, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000448', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 2761522.3000, ImporteAplicado = 2761519.7800, ImporteAplicado_Aux = 2761519.7800, ImporteRestante = 2.5200, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0030'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0031' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0031', 'OC-4550000449', '', '', '', 0, 1, 2, 0, 2761522.4000, 2761514.8500, 1258264.1800, 1503258.2200, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000449', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 2761522.4000, ImporteAplicado = 2761514.8500, ImporteAplicado_Aux = 1258264.1800, ImporteRestante = 1503258.2200, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0031'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0032' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0032', 'OC-4550000450', '', '', '', 0, 1, 2, 0, 2491209.6000, 0.0000, 0.0000, 2491209.6000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000450', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 2491209.6000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 2491209.6000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0032'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0033' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0033', 'OC-4550000451', '', '', '', 0, 1, 2, 0, 2103535.2000, 600631.7600, 0.0000, 2103535.2000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000451', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 2103535.2000, ImporteAplicado = 600631.7600, ImporteAplicado_Aux = 0.0000, ImporteRestante = 2103535.2000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0033'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0034' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0034', 'OC-4550000452', '', '', '', 0, 1, 2, 0, 1633548.5600, 1633545.6400, 0.0000, 1633548.5600, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000452', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 1633548.5600, ImporteAplicado = 1633545.6400, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1633548.5600, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0034'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0035' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0035', 'OC-4550000453', '', '', '', 0, 1, 2, 0, 4252765.2000, 0.0000, 0.0000, 4252765.2000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000453', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 4252765.2000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 4252765.2000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0035'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0036' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0036', 'OC-4550000454', '', '', '', 0, 1, 2, 0, 2325414.3600, 0.0000, 0.0000, 2325414.3600, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000454', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 2325414.3600, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 2325414.3600, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0036'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0037' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0037', 'OC-4550000455', '', '', '', 0, 1, 2, 0, 1224000.0000, 1223990.8200, 0.0000, 1224000.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000455', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 1224000.0000, ImporteAplicado = 1223990.8200, ImporteAplicado_Aux = 0.0000, ImporteRestante = 1224000.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0037'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0038' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0038', 'OC-4550000456', '', '', '', 0, 1, 2, 0, 4254265.2000, 4254264.6200, 2182619.4600, 2071645.7400, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000456', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 4254265.2000, ImporteAplicado = 4254264.6200, ImporteAplicado_Aux = 2182619.4600, ImporteRestante = 2071645.7400, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0038'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0039' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0039', 'OC-4550000457', '', '', '', 0, 1, 2, 0, 6330579.6000, 0.0000, 0.0000, 6330579.6000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000457', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 6330579.6000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 6330579.6000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0039'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0040' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0040', 'OC-4550000458', '', '', '', 0, 1, 2, 0, 7128252.0000, 0.0000, 0.0000, 7128252.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000458', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 7128252.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 7128252.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0040'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0041' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0041', 'OC-4550000459', '', '', '', 0, 1, 2, 0, 4142283.6000, 0.0000, 0.0000, 4142283.6000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000459', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 4142283.6000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 4142283.6000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0041'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0042' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0042', 'OC-4550000460', '', '', '', 0, 1, 2, 0, 3736814.4000, 0.0000, 0.0000, 3736814.4000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000460', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 3736814.4000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 3736814.4000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0042'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0043' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0043', 'OC-4550000461', '', '', '', 0, 1, 2, 0, 3155302.8000, 0.0000, 0.0000, 3155302.8000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000461', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 3155302.8000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 3155302.8000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0043'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0044' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0002', '0044', 'OC-4550000462', '', '', '', 0, 1, 2, 0, 2450322.8400, 0.0000, 0.0000, 2450322.8400, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000462', IdFuenteFinanciamiento_Relacionado = '', IdFinanciamiento_Relacionado = '', IdDocumento_Relacionado = '', EsRelacionado = 0, OrigenDeInsumo = 1, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 2450322.8400, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 2450322.8400, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0002' and IdDocumento = '0044'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0001' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0001', 'OC-4550000443-R', '0001', '0002', '0025', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000443-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0025', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0001'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0002' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0002', 'OC-4550000444-R', '0001', '0002', '0026', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000444-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0026', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0002'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0003' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0003', 'OC-4550000445-R', '0001', '0002', '0027', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000445-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0027', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0003'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0004' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0004', 'OC-4550000446-R', '0001', '0002', '0028', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000446-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0028', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0004'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0005' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0005', 'OC-4550000447-R', '0001', '0002', '0029', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000447-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0029', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0005'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0006' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0006', 'OC-4550000448-R', '0001', '0002', '0030', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000448-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0030', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0006'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0007' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0007', 'OC-4550000449-R', '0001', '0002', '0031', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000449-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0031', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0007'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0008' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0008', 'OC-4550000450-R', '0001', '0002', '0032', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000450-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0032', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0008'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0009' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0009', 'OC-4550000451-R', '0001', '0002', '0033', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000451-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0033', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0009'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0010' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0010', 'OC-4550000452-R', '0001', '0002', '0034', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000452-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0034', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0010'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0011' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0011', 'OC-4550000453-R', '0001', '0002', '0035', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000453-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0035', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0011'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0012' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0012', 'OC-4550000454-R', '0001', '0002', '0036', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000454-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0036', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0012'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0013' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0013', 'OC-4550000455-R', '0001', '0002', '0037', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000455-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0037', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0013'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0014' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0014', 'OC-4550000456-R', '0001', '0002', '0038', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000456-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0038', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0014'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0015' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0015', 'OC-4550000457-R', '0001', '0002', '0039', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000457-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0039', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0015'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0016' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0016', 'OC-4550000458-R', '0001', '0002', '0040', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000458-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0040', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0016'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0017' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0017', 'OC-4550000459-R', '0001', '0002', '0041', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000459-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0041', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0017'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0018' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0018', 'OC-4550000460-R', '0001', '0002', '0042', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000460-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0042', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0018'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0019' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0019', 'OC-4550000461-R', '0001', '0002', '0043', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000461-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0043', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0019'  
If Not Exists ( Select * From FACT_Fuentes_De_Financiamiento_Detalles_Documentos Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0020' )  Insert Into FACT_Fuentes_De_Financiamiento_Detalles_Documentos (  IdFuenteFinanciamiento, IdFinanciamiento, IdDocumento, NombreDocumento, IdFuenteFinanciamiento_Relacionado, IdFinanciamiento_Relacionado, IdDocumento_Relacionado, EsRelacionado, OrigenDeInsumo, TipoDeDocumento, TipoDeInsumo, ValorNominal, ImporteAplicado, ImporteAplicado_Aux, ImporteRestante, AplicaFarmacia, AplicaAlmacen, EsProgramaEspecial, Status, Actualizado, TipoDeBeneficiario )  Values ( '0001', '0003', '0020', 'OC-4550000462-R', '0001', '0002', '0044', 1, 2, 2, 0, 0.0000, 0.0000, 0.0000, 0.0000, 1, 1, 0, 'A', 0, 0 ) 
 Else Update FACT_Fuentes_De_Financiamiento_Detalles_Documentos Set NombreDocumento = 'OC-4550000462-R', IdFuenteFinanciamiento_Relacionado = '0001', IdFinanciamiento_Relacionado = '0002', IdDocumento_Relacionado = '0044', EsRelacionado = 1, OrigenDeInsumo = 2, TipoDeDocumento = 2, TipoDeInsumo = 0, ValorNominal = 0.0000, ImporteAplicado = 0.0000, ImporteAplicado_Aux = 0.0000, ImporteRestante = 0.0000, AplicaFarmacia = 1, AplicaAlmacen = 1, EsProgramaEspecial = 0, Status = 'A', Actualizado = 0, TipoDeBeneficiario = 0 Where IdFuenteFinanciamiento = '0001' and IdFinanciamiento = '0003' and IdDocumento = '0020'  


----------------------------------------------------------------- SOLO TAMAULIPAS 

Go--#SQL 
