If Exists ( Select * From Sysobjects (NoLock) Where Name = 'BI_UNI_RPT__DTS__ClavesSSA' and xType = 'U' ) 
   Drop Table BI_UNI_RPT__DTS__ClavesSSA 
Go--#SQL 

Create Table BI_UNI_RPT__DTS__ClavesSSA 
(
	Consecutivo int Not Null Default 0, 
	ClaveSSA varchar(20) Not Null Default '', 
	DescripcionSSA varchar(max) Not Null Default '', 
	Presentacion varchar(500) Not Null Default '', 
	CantidadMinima int Not Null Default 0, 
	CantidadMaxima int Not Null Default 0		
)
Go--#SQL    


 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 1, '010.000.0103.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 2, '010.000.0104.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 3, '010.000.0105.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 4, '010.000.0108.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 5, '010.000.0109.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 6, '010.000.0204.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 7, '010.000.0232.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 8, '010.000.0246.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 9, '010.000.0247.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 10, '010.000.0252.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 11, '010.000.0254.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 12, '010.000.0261.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 13, '010.000.0262.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 14, '010.000.0267.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 15, '010.000.0270.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 16, '010.000.0271.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 17, '010.000.0291.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 18, '010.000.0406.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 19, '010.000.0426.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 20, '010.000.0474.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 21, '010.000.0476.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 22, '010.000.0524.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 23, '010.000.0569.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 24, '010.000.0570.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 25, '010.000.0572.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 26, '010.000.0574.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 27, '010.000.0592.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 28, '010.000.0596.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 29, '010.000.0597.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 30, '010.000.0598.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 31, '010.000.0599.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 32, '010.000.0611.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 33, '010.000.0612.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 34, '010.000.0614.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 35, '010.000.0615.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 36, '010.000.0621.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 37, '010.000.0622.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 38, '010.000.0623.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 39, '010.000.0624.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 40, '010.000.1042.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 41, '010.000.1050.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 42, '010.000.1051.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 43, '010.000.1206.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 44, '010.000.1207.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 45, '010.000.1233.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 46, '010.000.1234.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 47, '010.000.1241.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 48, '010.000.1272.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 49, '010.000.1309.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 50, '010.000.1311.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 51, '010.000.1541.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 52, '010.000.1542.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 53, '010.000.1545.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 54, '010.000.1546.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 55, '010.000.1551.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 56, '010.000.1736.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 57, '010.000.1911.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 58, '010.000.1921.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 59, '010.000.1928.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 60, '010.000.1929.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 61, '010.000.1931.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 62, '010.000.1933.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 63, '010.000.1935.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 64, '010.000.1937.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 65, '010.000.1956.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 66, '010.000.1956.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 67, '010.000.1957.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 68, '010.000.1957.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 69, '010.000.1973.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 70, '010.000.2135.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 71, '010.000.2141.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 72, '010.000.2142.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 73, '010.000.2153.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 74, '010.000.2154.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 75, '010.000.2154.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 76, '010.000.2155.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 77, '010.000.2303.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 78, '010.000.2307.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 79, '010.000.2308.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 80, '010.000.2403.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 81, '010.000.2501.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 82, '010.000.2520.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 83, '010.000.2540.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 84, '010.000.2542.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 85, '010.000.3111.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 86, '010.000.3112.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 87, '010.000.3412.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 88, '010.000.3413.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 89, '010.000.3417.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 90, '010.000.3422.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 91, '010.000.3433.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 92, '010.000.3604.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 93, '010.000.3606.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 94, '010.000.3617.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 95, '010.000.3618.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 96, '010.000.3619.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 97, '010.000.3620.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 98, '010.000.3620.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 99, '010.000.3623.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 100, '010.000.3625.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 101, '010.000.3629.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 102, '010.000.3662.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 103, '010.000.4028.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 104, '010.000.4055.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 105, '010.000.4059.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 106, '010.000.4061.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 107, '010.000.4095.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 108, '010.000.4096.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 109, '010.000.4107.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 110, '010.000.4110.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 111, '010.000.4114.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 112, '010.000.4118.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 113, '010.000.4148.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 114, '010.000.4154.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 115, '010.000.4158.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 116, '010.000.4162.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 117, '010.000.4184.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 118, '010.000.4201.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 119, '010.000.4224.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 120, '010.000.4224.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 121, '010.000.4237.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 122, '010.000.4238.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 123, '010.000.4239.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 124, '010.000.4241.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 125, '010.000.4242.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 126, '010.000.4242.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 127, '010.000.4245.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 128, '010.000.4246.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 129, '010.000.4246.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 130, '010.000.4249.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 131, '010.000.4251.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 132, '010.000.4255.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 133, '010.000.4259.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 134, '010.000.4291.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 135, '010.000.5099.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 136, '010.000.5104.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 137, '010.000.5105.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 138, '010.000.5107.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 139, '010.000.5117.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 140, '010.000.5165.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 141, '010.000.5181.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 142, '010.000.5187.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 143, '010.000.5252.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 144, '010.000.5253.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 145, '010.000.5255.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 146, '010.000.5256.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 147, '010.000.5265.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 148, '010.000.5291.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 149, '010.000.5295.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 150, '010.000.5333.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 151, '010.000.5476.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 152, '010.000.5501.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 153, '020.000.3847.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 154, '020.000.3848.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 155, '020.000.3849.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 156, '040.000.0132.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 157, '040.000.0221.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 158, '040.000.0226.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 159, '040.000.0242.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 160, '040.000.0243.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 161, '040.000.0302.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 162, '040.000.2097.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 163, '040.000.2098.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 164, '040.000.2099.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 165, '040.000.2103.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 166, '040.000.2106.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 167, '040.000.2107.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 168, '040.000.2108.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 169, '040.000.2601.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 170, '040.000.2652.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 171, '040.000.2653.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 172, '040.000.3253.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 173, '040.000.3258.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 174, '040.000.4026.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 175, '040.000.4054.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 176, '040.000.4057.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 177, '040.000.4060.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 178, '040.000.4481.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 179, '010.000.1981.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 180, '010.000.2156.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 181, '010.000.2195.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 182, '010.000.4504.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 183, '040.000.2096.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 184, '010.000.5551.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 185, '010.000.5552.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 186, '010.000.4117.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 187, '010.000.0524.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 188, '010.000.0641.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 189, '010.000.3601.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 190, '010.000.3603.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 191, '010.000.3604.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 192, '010.000.3605.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 193, '010.000.3606.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 194, '010.000.3607.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 195, '010.000.3608.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 196, '010.000.3609.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 197, '010.000.3610.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 198, '010.000.3611.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 199, '010.000.3612.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 200, '010.000.3613.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 201, '010.000.3614.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 202, '010.000.3615.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 203, '010.000.3616.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 204, '010.000.3617.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 205, '010.000.3618.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 206, '010.000.3619.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 207, '010.000.3620.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 208, '010.000.3620.01', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 209, '010.000.3623.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 210, '010.000.3624.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 211, '010.000.3625.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 212, '010.000.3626.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 213, '010.000.3627.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 214, '010.000.3629.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 215, '010.000.3630.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 216, '010.000.3631.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 217, '010.000.3632.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 218, '010.000.3634.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 219, '010.000.3661.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 220, '010.000.3662.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 221, '010.000.3663.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 222, '010.000.3664.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 223, '010.000.3674.00', '', '', 0, 0 )   
 Insert Into BI_UNI_RPT__DTS__ClavesSSA (  Consecutivo, ClaveSSA, DescripcionSSA, Presentacion, CantidadMinima, CantidadMaxima )  Values ( 224, '010.000.3675.00', '', '', 0, 0 )   
 
 
	Update C set ClaveSSA = replace(ClaveSSA, 'U', '') 
	From BI_UNI_RPT__DTS__ClavesSSA C 


Go--#SQL 

