//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DllPedidosClientes.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DllPedidosClientes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Claves_Negadas_28 {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Claves_Negadas_28", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Claves_Negadas_29 {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Claves_Negadas_29", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Claves_Negadas_30 {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Claves_Negadas_30", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Claves_Negadas_31 {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Claves_Negadas_31", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_CortesDiarios_Farmacias {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_CortesDiarios_Farmacias", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Cuadros_Basicos {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Cuadros_Basicos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Cuadros_Basicos_Farmacias {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Cuadros_Basicos_Farmacias", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJuris_Claves_Negadas_28 {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJuris_Claves_Negadas_28", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJuris_Claves_Negadas_29 {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJuris_Claves_Negadas_29", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJuris_Claves_Negadas_30 {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJuris_Claves_Negadas_30", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJuris_Claves_Negadas_31 {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJuris_Claves_Negadas_31", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJuris_Dispensacion {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJuris_Dispensacion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJuris_Dispensacion_Concentrado {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJuris_Dispensacion_Concentrado", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJuris_Proximos_Caducar {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJuris_Proximos_Caducar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJuris_TBC_Surtimiento {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJuris_TBC_Surtimiento", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJuris_TBC_Surtimiento_NoCauses {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJuris_TBC_Surtimiento_NoCauses", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoJurisUnidad_Dispensacion {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoJurisUnidad_Dispensacion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoMovtos_Entradas {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoMovtos_Entradas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoMovtos_Salidas {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoMovtos_Salidas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_EdoMovtos_Transferencias {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_EdoMovtos_Transferencias", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Existencia_Claves {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Existencia_Claves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Nivel_De_Abasto {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Nivel_De_Abasto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Productos_Movimientos_Secretaria {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Productos_Movimientos_Secretaria", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Salidas_Antibioticos_Controlados {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Salidas_Antibioticos_Controlados", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Salidas_Costos_Programas_Atencion {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Salidas_Costos_Programas_Atencion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Salidas_Costos_Programas_Atencion_ConcentradoFarmacia {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Salidas_Costos_Programas_Atencion_ConcentradoFarmacia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Salidas_Medicos_Diagnosticos {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Salidas_Medicos_Diagnosticos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] CTE_REG_Surtimiento_Claves {
            get {
                object obj = ResourceManager.GetObject("CTE_REG_Surtimiento_Claves", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] Kardex_Antibioticos_Controlados_Farmacia {
            get {
                object obj = ResourceManager.GetObject("Kardex_Antibioticos_Controlados_Farmacia", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
