
USE MASTER

GO

DECLARE @DBID INT, @PORC INT, @NAME VARCHAR(255), @RECOVERY VARCHAR(50), @NAMELOG VARCHAR(255), @SQL NVARCHAR(4000),@RM VARCHAR(255)

DECLARE CURSOR_SP CURSOR FOR

SELECT DATABASE_ID,INSTANCE_NAME,CNTR_VALUE ,RECOVERY_MODEL_DESC

FROM SYSPERFINFO,SYS.DATABASES

WHERE COUNTER_NAME = 'PERCENT LOG USED' AND INSTANCE_NAME != '_TOTAL' AND NAME = INSTANCE_NAME AND NAME NOT IN ('TEMPDB','MSDB','MASTER','MODEL')

OPEN CURSOR_SP

FETCH NEXT FROM CURSOR_SP INTO @DBID,@NAME, @PORC,@RM

WHILE @@FETCH_STATUS = 0

BEGIN

 IF(@PORC >=90)

 BEGIN

  SELECT TOP 1 @NAMELOG = F.NAME FROM SYSALTFILES F WHERE GROUPID = 0 AND @DBID = DBID

  SET @SQL = 'USE [' + RTRIM(@NAME) +']' + CHAR(13) + 'CHECKPOINT' +  (CASE @RM WHEN 'FULL' THEN CHAR(13) +'ALTER DATABASE '+ RTRIM(@NAME) +' SET RECOVERY SIMPLE '  ELSE '' END )  + CHAR(13) + 'DBCC SHRINKFILE('''+RTRIM(@NAMELOG)+''', 1)' +  (CASE @RM WHEN 'FULL' THEN CHAR(13) +'ALTER DATABASE '+ RTRIM(@NAME) +' SET RECOVERY FULL ' ELSE '' END ) + CHAR(13)

  PRINT @SQL

  -- EXEC(@SQL) 

  Exec sp_TruncateLog @BaseDeDatos = @NAME, @Truncate = 1 

 END

    FETCH NEXT FROM CURSOR_SP INTO @DBID,@NAME, @PORC,@RM

END

CLOSE CURSOR_SP

DEALLOCATE CURSOR_SP